export type DeliveryStatus = "done" | "in-progress" | "pending" | "risk";

export type DeliveryMetric = {
  label: string;
  value: string;
  detail: string;
};

export type DeliveryWorkLog = {
  date: string;
  planned: string;
  completed: number;
  status: DeliveryStatus;
  codeWork: string[];
  valueDelivered: string[];
  evidence: string[];
};

export type DeliveryFocusItem = {
  title: string;
  owner: string;
  status: DeliveryStatus;
  percent: number;
  outcome: string;
};

export type DailyLaunchPlan = {
  date: string;
  title: string;
  objective: string;
  completionTarget: string;
  checkpoints: DeliveryFocusItem[];
};

export type SixDayFocus = {
  date: string;
  focus: string;
  output: string;
  riskControl: string;
};

export type LaunchVerdict = {
  title: string;
  status: DeliveryStatus;
  value: string;
  detail: string;
};

export type LiveReleaseGate = {
  step: number;
  title: string;
  status: DeliveryStatus;
  controlPlane: string;
  operatorAction: string;
  proofReceipt: string;
};

export const launchReadinessMetrics: DeliveryMetric[] = [
  {
    label: "Geography local funnel",
    value: "94%",
    detail: "Profile, Today, Learn, Discuss, MCQ, short Revisit, and Track are connected and browser-tested locally. Beginner routes to lesson-first while Intermediate and Advanced route to diagnosis-first; older inconsistent profiles self-heal before routing. Watch now exposes one player-level completion action without visible day jumping or an above-player skip shortcut; approved recordings auto-open Talk when playback ends. The command-room map and both folded Track maps lock future unfinished days while completed or evidence-bearing days stay open for backward review. Visual Lab remains genuinely optional: an incomplete learner can continue directly to MCQ or save a five-stage proof first. Day 1 weak intake is blocked, a reviewed 25-question set returns to a clean learner-only practice page, and India-map support remains optional. Final recorded media and the real student-grade MCQ corpus still need the content-production pass.",
  },
  {
    label: "Real student readiness",
    value: "55%",
    detail: "The local pilot is usable for internal rehearsal. Live Supabase migration, Google OAuth continuity, real Day 1 assets, fresh MCQs, and first-student feedback remain required before a public invite.",
  },
  {
    label: "Supabase durability",
    value: "70%",
    detail: "Profile and subject progress sync plus the distributed AI-limiter adapter are wired with migrations and static preflights. Learner writes now serialize so the newest state wins, newer offline state retries after authentication or reconnect, and logout or authenticated account switches clear learner-only local state. Apply the SQL, add the server-only backend key, and prove recovery across two real authenticated browser sessions.",
  },
  {
    label: "First student invite risk",
    value: "High until live proof",
    detail: "Do not share the production link until Supabase OAuth, cross-session continuity, and the real Geography Day 1 content loop pass together.",
  },
];

export const launchVerdictCards: LaunchVerdict[] = [
  {
    title: "May 24 plan verdict",
    status: "done",
    value: "Locally closed",
    detail:
      "Geography reached local production-pilot level: 30-day class packs, student loop, MCQ gate, Track/Revisit, testing cockpit, and admin tracker are built and verified.",
  },
  {
    title: "Still pending",
    status: "risk",
    value: "Live backend and content proof",
    detail:
      "Supabase migration, Google OAuth callback verification, cross-session recovery, real advanced MCQs, and final Day 1 media depth remain launch blockers.",
  },
  {
    title: "Current direction",
    status: "in-progress",
    value: "Stabilize before sharing",
    detail:
      "Geography stays first. Environment and other subjects remain paused until the live authenticated Geography loop completes a controlled feedback-and-repair cycle.",
  },
];

export const deliveryWorkLog: DeliveryWorkLog[] = [
  {
    date: "Before May 23",
    planned: "Convert the existing MCQ portal into the foundation for a broader UPSC learning portal.",
    completed: 65,
    status: "done",
    codeWork: [
      "Existing dashboard, admin console, exam, reports, question bank, and bulk upload baseline existed.",
      "Core local app structure was already present in the Next.js frontend.",
    ],
    valueDelivered: [
      "The MCQ portal became the base system instead of a disposable prototype.",
      "Admin and student shells were available for UPSC-specific expansion.",
    ],
    evidence: ["Routes already present under dashboard, admin, tests, reports, and bulk upload."],
  },
  {
    date: "May 23",
    planned: "Make Geography the first production pilot subject and stop depending on cloud/Firebase for local testing.",
    completed: 82,
    status: "done",
    codeWork: [
      "Restored local login bypass for localhost testing.",
      "Built Geography 30-day GS-compatible schedule and room structure.",
      "Connected Command, Watch, Talk, Track, Revisit, Visual Lab, and MCQ readiness routes.",
      "Fixed forward/backward day movement across Geography rooms.",
      "Added contextual MCQ upload for subject, day, batch, and return path.",
      "Removed checked old protected branding from UPSC local flows.",
    ],
    valueDelivered: [
      "A student can move through Geography as a subject portal instead of only seeing an MCQ page.",
      "The admin can upload Geography MCQs against the exact day and batch without accidental mismatch.",
      "Local testing became possible even when Firebase or cloud services are unavailable.",
    ],
    evidence: [
      "Geography shared navigation E2E passed.",
      "Geography bulk context E2E passed.",
      "Production build passed locally.",
    ],
  },
  {
    date: "May 24",
    planned: "Close the Geography production pilot gaps and create an admin launch tracker for daily accountability.",
    completed: 99,
    status: "in-progress",
    codeWork: [
      "Added Geography MCQ quality preflight gate for weak versus strong CSV validation.",
      "Wired Geography MCQ readiness to the strict Geography audit so count-only batches cannot unlock student practice.",
      "Exposed the ready-state MCQ quality score in the Geography command board for operator verification.",
      "Updated Geography MCQ browser proofs with stronger fresh MCQ rows and quality-score assertions.",
      "Added a controlled Geography pilot release decision so the admin can approve or pause link sharing locally.",
      "Added tester share rules and a step-by-step Geography Day 1 pilot script to the testing cockpit.",
      "Split the shareable student pilot route from the operator testing cockpit so testers do not see admin language.",
      "Added a dynamic current-action panel and first-tester script to the student pilot route.",
      "Added a shared student handoff strip across Watch, Talk, and Visual Lab for previous/next room clarity.",
      "Added a zero-progress pilot proof so a fresh tester can start from the student link without seeded learner state.",
      "Added a share-ready rehearsal from the public pilot link through lesson completion, 95% Talk clearance, fresh MCQ command, and feedback capture.",
      "Added a founder review checklist for Geography landing, Watch, Talk, Visual Lab, MCQ intake, Track/Revisit, and mobile fit.",
      "Blocked pilot approval until founder review checklist is complete and no open blocker feedback remains.",
      "Added a real GEO-D01 intake rule: Day 1 cannot import as a launch bank until 25 fresh audited MCQs are present.",
      "Hardened local MCQ command sync so Geography and Environment batches stay DRAFT unless their subject quality audit passes.",
      "Added all-day Geography MCQ production sweep for 30 sessions.",
      "Added this admin launch plan and delivery tracker.",
      "Verified Geography Watch to Talk handoff with scene proof and saved recap.",
      "Verified Talk classroom loop with AI teacher, peer challenge, examiner verdict, and next-route decision.",
      "Tightened Visual Lab so direct MCQ access stays locked until Talk proof and all five Lab proofs are saved.",
      "Verified Earth Layers, Monsoon, India Atlas, Lab completion, and Lab-to-MCQ routing in browser.",
      "Added a full Geography Day 1 student journey smoke from Watch through Talk, Visual Lab, MCQ outcome, Track, and Revisit.",
      "Added a controlled Geography testing cockpit and admin observation panel with local feedback capture.",
      "Staged the first Geography Day 1 content pack with ready video, notes, transcript summary, and Talk handoff preview.",
      "Standardized content placeholder behavior so missing class packs show planned status rather than a broken empty state.",
      "Expanded Geography Week 1 class packs for Days 1-7 with lesson promise, notes preview, transcript summary, and Talk handoff.",
      "Kept Day 8+ as explicit planned placeholders so incomplete content cannot look silently ready.",
      "Expanded Geography Week 2 class packs for Days 8-14 across India physiography, drainage, monsoon, climate, soils, resources, agriculture, and integrated map drill.",
      "Kept Day 15+ as explicit planned placeholders so Week 3 is not presented as production-ready before content is staged.",
      "Expanded Geography Week 3 class packs for Days 15-21 across population, settlements, economic activities, transport, industry, regional development, and human geography consolidation.",
      "Kept Day 22+ as explicit planned placeholders so Week 4 revision and atlas work are not presented as production-ready before content is staged.",
      "Expanded the final Geography block for Days 22-30 across atlas mastery, PYQ traps, disaster and environment bridge, mains application, full drill, weak repair, final mock, and command day.",
      "Added a non-Geography placeholder guard so Environment cannot accidentally look ready before its real class packs are staged.",
      "Added a final admin student share packet with the exact pilot link, tester cap, start instruction, stop rule, and feedback review rule.",
      "Added a student-facing pilot session guide with time window, resume rule, and finish-feedback rule.",
      "Added a Track closeout panel so completed Day 1 learners return to pilot feedback and still have a visible Revisit recovery route.",
      "Hardened the admin share packet so open Blocker feedback overrides prior approval and visibly stops link sharing.",
      "Hardened the student pilot route so open Blocker feedback pauses the shared link until the blocker is reviewed.",
      "Closed the student pause loophole by turning Day 1 path cards into non-clickable paused cards whenever sharing is blocked.",
      "Added live self-reported Blocker handling so saving Blocker feedback immediately pauses the student pilot route.",
      "Subscribed the student pilot route to local feedback/release events so admin review can resume the page without a manual refresh.",
    ],
    valueDelivered: [
      "Weak Geography MCQs are blocked before entering the local draft bank.",
      "Strong, properly mapped MCQs can be saved locally with quality metadata.",
      "Fresh MCQ count alone no longer opens student practice; rows must carry map or atlas anchors, mechanism explanation, syllabus link, and UPSC trap language.",
      "The operator can see a passed MCQ quality score before letting students enter practice.",
      "The testing link now has an operator sign-off layer before it is shared with real students.",
      "The student-facing pilot route now opens at /upsc/geography/pilot without exposing admin controls.",
      "The first tester can land on the pilot page and immediately see the correct next room plus the stuck rule.",
      "A fresh local student with no saved Geography progress now has a proven Start lesson path.",
      "Students now receive one current action at a time across lesson, discussion, and MCQ practice.",
      "The public pilot link now has an end-to-end rehearsal that reaches fresh MCQ practice and saves student feedback without entering through internal routes.",
      "The first tester receives one exact Day 1 path instead of improvising through the product.",
      "The founder review is now a visible checklist instead of an informal memory item.",
      "The admin cannot approve the student testing window until every launch-critical Day 1 surface is manually checked.",
      "A partial Day 1 MCQ file can no longer masquerade as a launch-ready bank.",
      "A 25-row audited GEO-D01 CSV becomes READY locally and rehydrates the Geography MCQ readiness room.",
      "The founder/admin view can now track what was planned, shipped, pending, and risky.",
      "A student can complete Watch scenes, carry the recap into Talk, answer the peer challenge, and receive a saved route decision.",
      "A student cannot skip discussion into MCQ readiness; the route only opens after the 95% recall target while Visual Lab remains optional support.",
      "A complete Day 1 learner path now proves forward and backward room connectivity, MCQ command outcome, mobile fit, and old-branding cleanup.",
      "The founder can share one controlled local testing route and review saved tester feedback from the admin launch board.",
      "Day 1 Watch now opens with a credible class pack instead of a generic empty simulator, while Day 2+ clearly shows planned placeholders.",
      "Week 1 Watch and Content Command now open with staged Geography class packs, while Week 2 remains visibly planned until content is ready.",
      "Week 2 India Map Command now opens with staged class packs, while Week 3 remains visibly planned until content is ready.",
      "Week 3 Human and Economic Geography now opens with staged class packs, while Week 4 remains visibly planned until content is ready.",
      "Geography now has 30/30 local class packs staged for Watch, Content Command, and Talk handoff, while non-Geography subjects still show planned placeholders.",
      "The admin now has one share-ready handoff block for sending the pilot link without losing the operating rules.",
      "A tester can now pause and return to the pilot page with clear instruction to resume from the current room.",
      "After MCQ command, Track now becomes a proper student closeout surface instead of ending the loop silently.",
      "If a tester reports a Blocker, the admin sees a stop-sharing alert until that item is reviewed.",
      "If a Blocker exists, the student link itself stops exposing the Start/Open action and shows a paused review state.",
      "A blocked pilot link no longer leaves secondary room links available below the paused state.",
      "A student who reports a Blocker receives a clear pause confirmation and the route locks without a page reload.",
      "When the admin reviews the Blocker, the student page can return to the correct Start/Continue action through the local feedback update event.",
    ],
    evidence: [
      "Geography quality gate E2E passed.",
      "Geography MCQ readiness preflight E2E passed for content pending, quality review, command-ready, desktop, and mobile states.",
      "Geography MCQ gate E2E passed for Talk gate, Lab gate, fresh batch quality score, local practice, Track update, desktop, and mobile states.",
      "Geography testing cockpit E2E now covers tester script, share rules, student pilot current action, student first-tester script, student feedback save, admin review, admin approval, release persistence, desktop, and mobile states.",
      "Geography zero-progress pilot E2E proves an approved first-time student sees Start lesson, opens the lesson, and does not receive pre-seeded progress.",
      "Geography share-ready rehearsal E2E proves the public pilot link can carry a fresh tester through lesson, 95% discussion clearance, fresh MCQ practice, and feedback capture.",
      "Geography testing cockpit E2E now verifies pilot approval stays paused until the founder review checklist reaches 7/7.",
      "Geography Day 1 MCQ intake E2E blocks a 1-row GEO-D01 CSV, accepts 25 audited rows, marks GEO-D01 READY, and verifies the MCQ readiness return path.",
      "Geography bulk context E2E passed after the new gate.",
      "Geography all-day MCQ production E2E passed for all 30 days.",
      "Geography Watch to Talk handoff E2E passed.",
      "Geography Talk classroom loop E2E passed.",
      "Geography Visual Lab MCQ bypass E2E passed.",
      "Geography Visual Lab broad regression E2E passed.",
      "Geography Day 1 full student journey E2E passed with Watch/Talk/Lab handoff assertions, no desktop/mobile overflow, no console errors, and 3/3 MCQ command outcome.",
      "Geography testing cockpit E2E covers link, feedback save, admin review, desktop, and mobile.",
      "Geography content pack E2E covers Content Command Day 1, Watch Day 1, planned Day 2 placeholder, and mobile Watch proof.",
      "Geography Week 1 content pack E2E covers Days 1-7 ready state, Day 8 placeholder discipline, desktop Watch Day 6, and mobile Watch Day 7.",
      "Geography Week 2 content pack E2E covers Days 8-14 ready state, Day 15 placeholder discipline, desktop Watch Day 10, and mobile Watch Day 14.",
      "Geography Week 3 content pack E2E covers Days 15-21 ready state, Day 22 placeholder discipline, desktop Watch Day 18, and mobile Watch Day 21.",
      "Geography final block content pack E2E covers Days 22-30 ready state, Environment placeholder discipline, desktop Watch Day 24, and mobile Watch Day 30.",
      "Admin launch plan E2E covers the final share packet, exact student pilot link, tester cap, start rule, stop rule, feedback review rule, desktop, and mobile.",
      "Geography zero-progress and share-ready rehearsal E2Es cover the student session guide, resume rule, finish rule, desktop, and mobile.",
      "Geography Day 1 full student journey E2E now covers Track closeout, return to pilot feedback, feedback persistence, and Revisit recovery ledger.",
      "Admin launch plan E2E now seeds open Blocker feedback, verifies stop-sharing override, then marks it reviewed and verifies approval resumes.",
      "Geography zero-progress pilot E2E now seeds open Blocker feedback, verifies the student link pauses, then reviews the blocker and verifies Start lesson returns.",
      "Geography zero-progress pilot E2E now also verifies paused Day 1 path cards are not clickable links while Blocker feedback is open.",
      "Geography zero-progress pilot E2E now saves Blocker feedback from the student form and verifies immediate pause without reload.",
      "Geography zero-progress pilot E2E now marks that Blocker reviewed through the local event and verifies the student route resumes without reloading.",
    ],
  },
  {
    date: "May 31",
    planned: "Audit the student-visible portal, harden Supabase readiness, and remove unsafe or misleading pilot surfaces before live testing.",
    completed: 93,
    status: "in-progress",
    codeWork: [
      "Simplified the student shell to Today, Gaps, Revise, and Progress.",
      "Added offline-first Supabase profile and per-subject progress synchronization with RLS migration.",
      "Restricted local preview and mock-token use to localhost testing hosts.",
      "Protected UPSC command, audit, revision, Geography testing, legacy exam, simulation, and admin surfaces behind explicit master access.",
      "Replaced unsigned audit-API JWT decoding with verified Supabase session lookup.",
      "Added local static Supabase preflight, post-migration SQL checks, and live-apply checklist.",
      "Removed the dead public preview login button and the student-facing Revision Command roadmap leak.",
      "Added a protected Feature Inventory so the verified local ledger, live release gates, and Morning Batch V2 summary are visible inside the operator console.",
      "Audited the founder Geography corpus and added a protected Day 1 real-content intake packet with reusable sources, founder-required assets, and a proposed Day 1 and Day 2 split.",
      "Replaced the legacy admin dashboard sample metrics, unrelated subject chart, fabricated integrity counters, and backend-dependent recalibration control with an honest UPSC operator console.",
      "Replaced fabricated Founder Health metrics with a real seven-point Geography founder-review center and isolated legacy Observability, Analytics, and Test Management routes behind explicit dependency notices.",
      "Added an explicit legacy-API feature flag and defaulted the UPSC pilot to local draft mode for Question Bank and Bulk Upload.",
      "Replaced the weak demonstration CSV row with a UPSC-style Geography sample that passes the strict quality preflight.",
      "Converted Integrity Logs into an honest read-only local-control view and removed its non-functional healthy-status button.",
      "Generated an authoritative 89-page route inventory and added a role-aware browser crawler for public, learner, master-only, redirect, and isolated surfaces.",
      "Generated a source-derived subject-content maturity matrix across all eight subjects, 201 planned study days, 62 lab routes, staged class packs, and founder-approved live-pack boundaries.",
      "Converted the learner roadmap into one active Geography pilot card plus non-clickable future-subject cards, and protected Environment through History as master-inspection scaffolds.",
      "Relabeled Content Command as a local rehearsal surface so staged Geography packs cannot be mistaken for founder-approved live lecture media or student-release approval.",
      "Added one-question preparation-history intake that identifies Beginner, Intermediate, or Advanced while leaving study preferences optional.",
      "Rewired the Geography learner slice into a level-aware guided session: Beginner starts with one 10-15 minute lesson; Intermediate and Advanced start with explanation-first diagnosis.",
      "Added browser speech capture, local mastery hints, a 95% recall gate, and direct fresh-MCQ progression while retaining Visual Lab as optional support.",
      "Added a learner-authenticated adaptive-teacher API route with server-only Gemini configuration, structured JSON output, timeout handling, and deterministic local fallback.",
      "Replaced the hardcoded Day 1 dashboard topic with a generated Geography syllabus path that advances after MCQ command and scales from one to three topics by study window.",
      "Removed the remaining Visual-Lab scoring dependency, folded syllabus depth behind optional disclosure, removed learner-visible admin MCQ controls, and reduced Track closeout to one next-topic action.",
      "Added a learner-authenticated adaptive-teacher burst limit with no-store 429 responses and Retry-After guidance before live provider activation.",
      "Version-tagged adaptive-teacher prompts and rubrics and persisted the teacher trace with each Geography Talk result.",
      "Added a repeatable three-band adaptive-teacher evaluation harness and an explicit live Gemini activation checklist.",
      "Added a Supabase-backed adaptive-teacher rate-limit migration, server-only secret adapter, hashed request identity, privilege verification SQL, and a non-local fail-closed release boundary.",
      "Hardened the Talk transition so duplicate checks stay disabled while the teacher responds, edited drafts ignore stale coaching responses, and temporary provider failures preserve one local next action.",
      "Replaced the broad Earth-system Day 1 placeholder with a source-backed 12-minute Geography Foundation lesson: what, where, why; absolute-relative location; site-situation; scale; and India map relationships.",
      "Added a Day 1 India-map visual drill with five source-backed relationship choices and one-tap proof starters before the optional MCQ handoff.",
      "Added a safe committed environment template and a no-secret launch preflight that separates local readiness from live apply work.",
      "Linked the frontend workspace to the existing Vercel upsc-command project and added only the browser-safe Supabase variables across production, preview, and development.",
      "Created a protected Vercel preview deployment from the current 90-route build without promoting it to production.",
      "Simplified the shareable Geography pilot to exactly three primary learner steps: Learn, Discuss, and MCQ.",
      "Removed the stale mandatory Visual Lab branch from the pilot and operator cockpit; India-map support remains an optional learner tool.",
      "Aligned experienced-learner plan copy so a cleared explanation routes to fresh MCQ without implying an extra visual-proof requirement.",
      "Converted the three pilot path cards into read-only orientation steps so learners cannot jump ahead of the single current action.",
      "Normalized all 30 Geography lesson labels to the 12-minute short-topic contract already delivered by the five-checkpoint lesson engine.",
      "Added an explicit Geography Day 1 approved-media contract: browser-safe recording and transcript URLs, founder approval flag, real video rendering when configured, and an honest portal-native fallback until the assets arrive.",
      "Promoted Day 2 into the source-backed Origin and Evolution of Earth lesson with a five-stage Universe-to-Earth visual sequence: expansion, gravity, accretion, differentiation, and atmosphere-hydrosphere formation.",
      "Tightened Day 3 into the Interior of Earth and Plate Movement bridge so the 30-day schedule preserves seismic evidence, layers, mantle behavior, boundary types, and hazard-map logic.",
      "Promoted the Day 3 interior-to-plates bridge into a five-stage learner visual and reused it inside the optional Earth Layers lab: seismic evidence, layers, convection, boundaries, and hazard clustering.",
      "Upgraded the Day 3 learner visual so the existing Play action circulates mantle-current markers while the five-stage explanation advances.",
      "Reduced the Geography MCQ room to one learner-only next action, persisted completed outcomes across reload, and connected weak scores to one short revision note before Talk resumes.",
      "Locked each Geography MCQ after its first reviewed answer, blocked unanswered skip-ahead, hid the competing route panel during active practice, and preserved backward question review.",
      "Reduced Track to one Today's Task action, converted gap, revision, and trend into read-only signals, folded diagnostics and the 30-day map, and removed the duplicate closeout path.",
      "Closed the Day 1 bulk-upload handoff so operator toasts are dismissed before the learner preview opens.",
      "Added a 13-second browser-side adaptive-teacher timeout so a stalled provider request releases the learner back to the local guidance path.",
      "Serialized learner profile and subject-progress uploads so an older slow response cannot overwrite a newer local state remotely.",
      "Cleared learner-only local profile, progress, account marker, and localhost preview token on logout while reconciling authenticated account switches.",
      "Added profile, Geography-progress, and shared-subject recovery retries so newer offline state pushes after hydration or browser reconnect.",
      "Rechecked the mounted UPSC profile gate after learner-state cleanup so a shared-browser account switch cannot leave the previous learner's room visible.",
      "Removed visible Watch-room day jumping and the premature above-player completion shortcut, kept one player-level handoff action, and wired approved recording playback completion directly into Talk.",
      "Converted the folded generated daily syllabus queue into read-only Current and Queued cards so the main Today action remains the only executable learner route.",
      "Converted the folded Learn, Discuss, and MCQ dashboard cards into read-only orientation and removed the drawer's duplicate start action, leaving Today as the only study-room route on the dashboard.",
      "Locked future unfinished Geography command-room day cards, clamped typed untouched-future URLs back to the current topic, and preserved completed or evidence-bearing backward review inside the optional 30-day map.",
      "Locked untouched future Geography Track cards in both folded 30-day maps, preserved saved historical review links, and removed the redundant deep loop switcher.",
      "Made Visual Lab genuinely optional by replacing its incomplete-state save gate with a quiet direct MCQ return while preserving the save-and-open-MCQ evidence path.",
      "Required one meaningful optional Visual Lab note before save-and-open-MCQ can record its five-stage evidence receipt, while the direct MCQ bypass remains available.",
      "Normalized saved learner profiles at the persistence boundary so stale or contradictory legacy records cannot reopen the wrong Beginner, Intermediate, or Advanced route.",
      "Replaced the retired self-study intake browser proof with a current progressive-disclosure rehearsal and verified all three classification routes on desktop and mobile.",
      "Closed the cleared-recall Watch revisit edge case so a Beginner at 95% or above sees MCQ practice instead of reopening the lesson or discussion.",
      "Removed raw Talk-room route-stage labels from the learner score card while preserving recall score, teacher guidance, and the single next action.",
      "Reduced Talk to one AI-teacher prompt and one route: below-target recall keeps one mastery repair plan, while a cleared response removes the duplicate mastery panel and steady-state backend labels before MCQ handoff.",
      "Switched the production build script to Next.js Webpack mode after the Windows Turbopack bundle emitted missing dynamic client-chunk references for UPSC room routes.",
      "Hardened the adaptive-teacher request and provider boundary with JSON-only input, learner-request byte limits, provider-response byte limits, structured coach length limits, and strict oversized-output fallback.",
      "Added a strict browser-side adaptive-teacher response parser so malformed successful payloads fall back to quiet local guidance instead of entering learner state.",
      "Tightened the Day 1 approved-media contract so learner video activation requires the approved recording and transcript pair; partial attachment stays on the portal-native fallback.",
      "Upgraded the protected Universe storyboard player with continuous tilted-Earth orbital motion during Play while preserving the compact learner-safe Day 2 visual.",
      "Upgraded the protected Earth-interior storyboard player with counter-moving mantle-current markers so the causal mechanism before plate boundaries is visible during Play.",
      "Upgraded the protected Volcanism storyboard player with continuous magma ascent, effusive lava advance, and explosive ash lift during Play.",
    ],
    valueDelivered: [
      "Students see one simple Geography learning path and cannot accidentally enter incomplete operator or legacy exam tools.",
      "Local learner state is ready to sync to Supabase after the live migration is applied.",
      "Internal audit APIs reject ordinary learner tokens and forged master-email JWTs.",
      "The remaining release boundary is explicit: live migration, OAuth rehearsal, real Day 1 content, and controlled feedback.",
      "The operator can now inspect verified, partial, external-apply, and isolated features without reading a separate Markdown report.",
      "The Day 1 content decision is now anchored to founder files instead of a generic staged pack, without destabilizing the currently verified student funnel.",
      "The default admin landing screen now reports only verified local readiness and explicit open gates.",
      "Direct visits to unsupported admin routes now explain their missing dependencies instead of implying live functionality.",
      "Fresh MCQ authoring no longer creates avoidable localhost:8000 errors: the local quality gate, draft storage, review bank, and Geography handoff work directly while live publishing stays isolated.",
      "Integrity Logs now distinguishes verified local controls from isolated live dependencies without implying production health.",
      "Every concrete page route now has an explicit access classification and a passing rendered smoke result.",
      "The operator can now distinguish teaching scaffolds from real launch assets: Geography has 30 local rehearsal definitions, Days 1 and 2 remain portal-native drafts, 28 packs are staged locally, founder-approved live packs remain at zero, and later subjects remain planned.",
      "Students can no longer wander into future subject rooms before their real class packs are produced; masters retain direct access for development and review.",
      "Operators now see locally staged class-pack status without a false implication that real lecture assets are approved for launch.",
      "A new learner sees only Learn, Discuss, and MCQ. Experienced students skip generic teaching until their explanation exposes a specific repair gap.",
      "The remaining teacher boundary is explicit: local adaptive routing works, but live Gemini conversation, streaming, and evaluation still require server-side integration.",
      "Malformed, non-JSON, oversized learner requests and oversized provider coaching can no longer expand the Talk surface or destabilize the learner loop.",
      "A malformed successful teacher response can no longer persist broken trace data or remove the learner's next action.",
      "A half-attached Day 1 media pack can no longer appear as an approved learner video before its transcript is attached.",
      "The first Animation Studio pilot now demonstrates real portal motion instead of only stepped storyboard snapshots, without exposing operator controls to learners.",
      "The Earth-interior pilot now makes mantle convection visible before students move into plate boundaries and volcanism.",
      "The Volcanism pilot now turns eruption mechanics into visible motion without changing the UPSC teaching sequence or adding learner-facing controls.",
      "Verified all 24 Geography Animation Studio portal previews in the operator-only catalog while keeping export-grade Remotion, HyperFrames, or Three.js production as an explicit open track.",
      "The browser never receives a Gemini key: provider access is isolated behind a learner-authenticated no-store server endpoint.",
      "Today no longer stalls on the first Geography class: MCQ command moves the learner into the next syllabus topic while preserving lesson-first versus diagnosis-first routing.",
      "Track no longer leaks pilot-feedback, gate-proof, or admin-upload decisions into the learner's primary path. Visual Lab remains enrichment and cannot reduce an otherwise complete command score.",
      "The adaptive-teacher boundary now rejects request bursts locally; a durable distributed limiter remains an explicit live-release requirement.",
      "Teacher feedback now carries an auditable prompt version, rubric version, recall target, mode, and saved coaching prompt for later live-provider evaluation.",
      "Weak, developing, and command answer bands now have deterministic local regression evidence before provider activation.",
      "Local Talk rehearsal remains offline-friendly, while deployed Talk requests now refuse service until the Supabase distributed limiter is applied and its server-only secret is configured.",
      "A temporary AI delay or outage no longer creates conflicting guidance or a dead end for the learner.",
      "A beginner now receives a real Day 1 foundation sequence with five concise checkpoints and an India-map Talk handoff while final lecture production and fresh MCQs stay visibly open.",
      "Day 1 visual repair now teaches an actual relationship instead of asking for a generic note: the selected map link and its UPSC trap persist with the learner proof.",
      "Deployment setup is no longer ambiguous: the workspace targets the existing upsc-command Vercel project, while server secrets and live SQL remain explicit operator actions.",
      "A protected Vercel preview artifact now exists for remote QA without changing the public production alias.",
      "The controlled tester link now teaches the same simple rule as the dashboard: complete one lesson, discuss to 95% recall, then attempt fresh MCQs.",
      "A learner who clears discussion at 96/100 reaches MCQ directly while the optional India-map helper remains one click away.",
      "The controlled tester page now gives one actionable next step at a time; the three-step path is visible for orientation without becoming a skip menu.",
      "Every Geography day now presents one 12-minute learner topic instead of leaking the older 60-120 minute block labels into the simplified experience.",
      "A final Day 1 recording can now replace the fallback without rewriting the learner flow, while the operator console visibly keeps the release gate open until recording and transcript are attached.",
      "A beginner opening Day 2 now receives one visual causal chain and one Discuss handoff instead of a disconnected universe-facts wrapper, while the optional lab route remains available for deeper review.",
      "A beginner opening Day 3 now moves from seismic-wave evidence to plate-boundary outcomes in one compact lesson, and can replay the same visual inside optional Earth Layers review after discussion clearance.",
      "A beginner opening Day 4 now distinguishes weathering from erosion, follows sediment into deposition, and connects gravity with slope failure before optional Disaster Link review.",
      "A beginner opening Day 5 now derives planetary winds from unequal heating, pressure gradient, circulation, and Coriolis deflection before optional Monsoon Simulator review.",
      "A beginner opening Day 6 now connects ocean relief, water properties, circulation, coastal effects, and current-location pairs before optional Monsoon Simulator review.",
      "A beginner opening Day 7 now consolidates location, tectonics, geomorphic processes, climate, and ocean systems into one answer method before optional Earth Layers review.",
      "A beginner opening Day 8 now reads India physiography as one relief framework, then connects mountains, plains, plateau, desert, coasts, and islands with rivers, climate, resources, and risk before optional India-map review.",
      "A beginner opening Day 9 now traces Indian drainage through source, slope, basin, tributaries, outlet, and consequence before optional India-map review.",
      "A beginner opening Day 10 now explains Indian monsoon through thermal contrast, ITCZ movement, moisture branches, active-break-retreat rhythm, and bounded variability signals before optional simulator review.",
      "A beginner opening Day 11 now compares Indian climate regions through latitude, altitude, relief, sea distance, winds, rain shadow, western disturbances, and temperature range before optional simulator review.",
      "A beginner opening Day 12 now connects soil formation, soil families, vegetation response, degradation pressure, and conservation before optional Environment Bridge review.",
      "A beginner opening Day 13 now explains resource and crop belts through location factors, minerals and energy, agro-climatic suitability, irrigation pressure, and swapped-pair traps before optional India Interactive Map review.",
      "A beginner opening Day 14 now consolidates India Map Command through relief, drainage, climate, productive belts, mixed-region traps, and five weak-location repair cards before optional India Interactive Map review.",
      "A beginner opening Day 15 now explains population geography through indicator discipline, concentration factors, migration, demographic transition, and swapped-indicator traps before optional India Interactive Map review.",
      "A beginner opening Day 16 now classifies settlements through site, situation, rural patterns, urban hierarchy, morphology, function, and cross-matched classification traps before optional India Interactive Map review.",
      "A beginner opening Day 17 now explains economic activities through extraction, transformation, services, knowledge, decisions, structural change, and overlap traps before optional India Interactive Map review.",
      "A beginner opening Day 18 now explains transport and trade through network logic, transport modes, ports, hinterland, regional change, and map mismatches before optional India Interactive Map review.",
      "A beginner opening Day 19 now explains industry location through classical factors, modern factors, old regions, new clusters, changing context, and factor-example mismatches before optional India Interactive Map review.",
      "A beginner opening Day 20 now explains regional development through spatial gaps, planning regions, growth-pole pressure, governance response, sustainability, and solution mismatches before optional Environment Bridge review.",
      "A beginner opening Day 21 now consolidates human geography through people, settlements, activity chains, networks, regional outcomes, and weak-link repair before optional India Interactive Map review.",
      "A beginner opening Day 22 now converts atlas reading into exam recall through orientation, neighbors, layered maps, quick context, and nearby-location trap discipline before optional India Interactive Map review.",
      "A beginner opening Day 23 now reads PYQ-style statements through tested idea, order, location, pairs, exceptions, explanation validity, and repair-card discipline before optional MCQ Engine review.",
      "A beginner opening Day 24 now connects physical geography with disaster management through hazard, exposure, vulnerability, capacity, response, and mismatch discipline before optional Disaster Link review.",
      "A beginner opening Day 25 now connects geography with environment through biome controls, habitat, biodiversity, climate exposure, conservation regions, and cross-match discipline before optional Environment Bridge review.",
      "A beginner opening Day 26 now converts Geography knowledge into a 10-marker through context, causal mechanism, spatial proof, example, conclusion, and fact-dump repair before optional India Interactive Map review.",
      "A beginner opening Day 27 now runs the full Geography drill through physical base, India map, human outcomes, environment and disaster bridges, and weak-area heatmap repair before optional MCQ Engine review.",
      "A beginner opening Day 28 now repairs tracked weakness through mistake classification, root cause, narrow repair cards, fresh retest, and revision scheduling before optional MCQ Engine review.",
      "A beginner opening Day 29 now converts the final mock into a 24-hour repair queue through score interpretation, error classification, map repair, priority, and confidence control before optional MCQ Engine review.",
      "A beginner opening Day 30 now closes Geography through full recall, map confidence, learning-proof audit, revision lock, and an honest command-ready, revision-needed, or retest-needed verdict before optional India Interactive Map review.",
      "The Day 1 MCQ boundary now rejects a weak one-question import, accepts a reviewed 25-question proof set, and returns to a clean learner-only practice page without operator wording.",
      "A stalled teacher-network request no longer keeps the learner's discussion action disabled indefinitely; the proven local recommendation and route remain available.",
      "Rapid learner saves now coalesce behind one remote write queue, and shared-browser logout no longer leaves a previous student's UPSC profile or Geography progress behind.",
      "A learner who studies while offline can reconnect without making another edit: the latest local profile and progress snapshot retries through the same serialized queue.",
      "If learner identity changes while an UPSC room is already open, the room immediately returns behind the self-study profile gate until the new account is hydrated.",
      "A beginner now reaches the lesson before seeing its completion action: Watch exposes no premature shortcut or visible day switcher, saves one five-checkpoint handoff from the player, and moves an approved finished recording directly into discussion.",
      "A learner can see the compact time-aware syllabus allocation without choosing among future routes: the folded daily queue exposes zero skip-ahead links while Today advances automatically after MCQ command.",
      "The optional dashboard drawer no longer behaves like a second navigation surface: it keeps three orientation cards and exposes zero study-room links inside the current-flow panel.",
      "The optional Geography command-room map now supports review without becoming a skip menu: fresh Day 1 cannot open Day 5 or Day 10 even through a typed query, while completed or evidence-bearing days remain reviewable.",
      "Track now follows the same no-skip rule: saved learner evidence remains reviewable, untouched future topics are read-only, and the advanced panel no longer exposes a second day switcher.",
      "A learner who opens optional Visual Lab can leave for MCQ immediately without fabricating a saved visual proof; learners who want enrichment must write one meaningful note before saving all five proof stages and continuing.",
      "A returning learner with an older inconsistent profile is repaired into one coherent preparation stage, level, attempt history, and first study action before the dashboard opens.",
      "A learner who already cleared recall cannot accidentally loop backward through Watch: direct lesson revisits now expose only the MCQ continuation.",
      "Talk now keeps implementation stages internal: the learner sees one answer, one repair question when needed, one recall score, and one next action.",
      "The local production bundle now uses the stable Webpack builder and no longer intermittently ships missing dynamic room chunks.",
    ],
    evidence: [
      "Production build passes with 90 routes, including the protected operator Feature Inventory.",
      "Student dashboard, signal pages, self-study intake, role-boundary, marketing entry, and Prelims V2 verifiers pass.",
      "Supabase static preflight passes 27 checks, including serialized remote writes, offline recovery retries, mounted profile-gate recheck, account-switch reconciliation, learner-state cleanup, and localhost preview-token cleanup.",
      "Level-aware guided-session and Watch-simple browser proofs pass against the rebuilt bundle with zero above-player Watch actions, one player-level completion action, five-checkpoint Talk handoff persistence, desktop fit, and mobile fit.",
      "Generated daily-path browser proof passes against the rebuilt bundle: Today advances from Day 1 to Day 2 after MCQ command, 120-minute and 180-minute plans retain the correct queue sizes, Current and Queued labels render, and the queue exposes zero direct links.",
      "Student-dashboard browser proof passes against the rebuilt bundle with exactly four visible dashboard decisions, a folded planning drawer, three read-only current-flow orientation cards, and zero drawer study-room links.",
      "Geography command-room simple-entry proof passes against the rebuilt bundle with fresh Day 1 future-day locks, typed untouched-future URL clamping, completed-day backward review, desktop fit, and mobile fit.",
      "Geography Track diagnostics proof passes against the rebuilt bundle with locked untouched Day 8 cards in both folded maps, historical Day 3 Revisit routing, completed Day 1 to Day 2 progression, zero redundant deep switchers, desktop fit, and mobile fit.",
      "Geography Visual Lab proof passes against the rebuilt bundle with folded advanced controls, an incomplete-state direct MCQ return, a meaningful-note save gate, persisted five-stage visual evidence, MCQ handoff, desktop fit, and mobile fit.",
      "Role-boundary verifier proves learner and forged JWT rejection plus explicit local master access.",
      "Feature Inventory browser verifier passes desktop, mobile, no-overflow, retired-branding cleanup, and learner redirect checks.",
      "The same protected inventory verifier confirms the Geography Day 1 source packet and founder-required asset rows render cleanly.",
      "Operator dashboard browser verifier rejects legacy demo copy, passes desktop and mobile fit, and proves learner redirect to Today.",
      "Admin-route isolation verifier passes Founder Review desktop/mobile, isolated route notices, retired-branding cleanup, and learner redirect checks.",
      "Bulk-upload UPSC CSV verifier passes desktop/mobile fit, strict Geography quality preflight, local draft storage, question-bank review, Geography day-room handoff, and zero failed legacy API requests.",
      "Admin-route isolation verifier now also covers the read-only Integrity Logs status and retired-branding sweep.",
      "Full route-matrix verifier visits 89/89 concrete pages with expected destinations, no blank pages, no framework overlays, no retired branding, no unexpected legacy API failures, and no horizontal overflow.",
      "Subject-readiness generator records eight subjects, 201 planned study days, 62 lab routes, 30 Geography rehearsal definitions, 24 Geography animation blueprints, 32 Geography catalog topics, and zero founder-approved live packs. Content Command reports 28/30 staged locally while Days 1 and 2 remain portal-native drafts.",
      "Future-subject isolation verifier proves the roadmap exposes one active Geography link, seven non-clickable planned cards, learner redirects for Environment and History rooms, and retained master inspection access.",
      "Content rehearsal-boundary verifier proves staged-local labels, the explicit live-release warning, desktop/mobile fit, and learner redirect behavior.",
      "Level-aware guided-session verifier proves Beginner lesson-first entry, Intermediate diagnosis-first entry, Advanced direct-MCQ routing after a 96% recall score, optional Visual Lab, speech-control presence, large lesson-player layout, and mobile no-overflow behavior.",
      "Adaptive-teacher API verifier proves unauthorized rejection, invalid-payload rejection, no-store structured fallback, provider-key isolation, trace versioning, and 12-request burst limiting while the Talk verifier proves the mastery plan renders, persists its trace, and preserves the honest repair route.",
      "Generated daily-path verifier proves Beginner Day 1 to Day 2 advancement, 120-minute two-topic queues, 180-minute three-topic queues, experienced diagnosis-first entry, and mobile fit.",
      "Track diagnostics verifier proves the 30-day map stays folded, revisit routing remains correct, a completed advanced Day 1 opens Day 2 diagnosis directly, and desktop/mobile layouts have no overflow.",
      "Command next-action verifier proves diagnosis-first entry, precise repair-lesson routing, MCQ authoring states, folded day controls, Track consistency, and mobile fit.",
      "Adaptive-teacher evaluation verifier proves stable weak, developing, and command score bands against the versioned Day 1 rubric.",
      "Adaptive-teacher production-boundary static verifier proves the distributed limiter migration, restricted RPC grant, hashed identity, server-only secret adapter, local fallback, and non-local fail-closed behavior.",
      "Adaptive-teacher transition browser verifier proves duplicate-submit blocking, stale-response rejection, provider-failure fallback, direct repair routing, and no horizontal overflow.",
      "Geography Day 1 source-backed Watch verifier proves the 12-minute lesson, five founder-corpus checkpoints, India-map handoff, Talk transition, and mobile fit.",
      "Geography Day 1 map-relationship Lab verifier proves Talk clearance, a source-backed Shipki La relationship prompt, saved India-map evidence, MCQ handoff, and mobile fit.",
      "Cleaned Geography content-pack verifiers prove the current honest rehearsal boundary: Days 1 and 2 are source-backed but IN PROGRESS, Days 3-8 are STAGED LOCAL, and desktop/mobile layouts have no overflow.",
      "Launch-environment preflight proves the local Supabase browser configuration and both prepared migrations without exposing credentials, while keeping Vercel link, server secrets, live SQL apply, OAuth, and continuity rehearsal explicitly pending.",
      "Vercel preview deployment upsc-command-fmor3qfx1-ktej255-gmailcoms-projects.vercel.app is READY; authenticated edge checks return 200 for / and /login and the intended 403 Learner access required for an unauthenticated teacher request.",
      "Geography simple-loop pilot verifier proves the shareable route exposes exactly Learn, Discuss, and MCQ, routes a 96/100 discussion directly into MCQ, retains optional India-map support, and fits desktop/mobile without overflow.",
      "The same simple-loop proof confirms the three orientation cards expose zero jump links.",
      "Updated zero-progress pilot regression proves check-in, lesson entry without auto-completion, blocker self-report, immediate pause, reviewed-blocker resume, desktop/mobile fit, and zero skip-ahead card links.",
      "Updated testing-cockpit regression proves founder checklist persistence, approval persistence, student check-in, feedback receipt, roster completion, and no retired-brand leakage under the simplified loop.",
      "Updated share-ready rehearsal proves the public tester link carries a fresh beginner through check-in, the 12-minute lesson, 96% Talk clearance, a reviewed GEO-D01 fresh MCQ set, 2/2 command, feedback capture, optional India-map support, and mobile fit.",
      "Geography 30-day simple-flow verifier proves all 30 command pages and all 30 lesson pages expose the 12-minute topic contract, retain exactly three primary steps, fit desktop and mobile, and emit no browser errors.",
      "Modernized Geography final-audit regression proves the current simplified Day 13 path from 12-minute lesson through 100% Talk clearance, reviewed 2/2 MCQ command, and Day 14 routing, plus the Day 10 weak-answer branch through one saved short revision back to Talk-ready recovery on desktop and mobile.",
      "Repaired Week 2-4 content-pack verifiers prove Days 8-30 render as STAGED LOCAL in the operator console, the simplified learner pages expose the 12-minute lesson player without retired asset-panel copy, Environment remains a planned placeholder, and desktop/mobile layouts emit no browser errors or retired branding.",
      "Final compiled-bundle sweep passes typecheck, the 90-route production build, the 89/89 role-aware route matrix, learner-versus-master access gates, the public Geography rehearsal, the launch board, the feature inventory, simple Geography entry, Talk repair routing, and Week 1-4 staged-content checks.",
      "June 3 rebuilt content-depth sweep passes 30/30 static Geography lesson/media contracts, Week 1-4 browser content packs, the final Geography audit, and the 89/89 route matrix.",
      "Day 1 approved-media contract static verifier passes 14 checks, while its browser rehearsal proves the operator receipt, honest portal-native fallback, absent fake approved video, desktop/mobile fit, and zero browser errors.",
      "Integrated Geography MCQ verifier proves calm preparing state, reviewed practice, persisted command and weak outcomes, exactly one learner continuation action, short-Revisit continuity, Day 1 one-question intake rejection, reviewed 25-question acceptance, clean learner handoff, desktop/mobile fit, and zero browser errors.",
      "Geography Revisit verifier proves one required correction note, a folded optional recovery checklist, one pending action, one completed return-to-discussion action, persisted repair evidence, and desktop/mobile fit. The refreshed continuity verifier also proves Environment learner routes remain gated while that subject is still a future scaffold.",
      "Geography Track closeout verifiers prove one focused next action, three compact signals, folded 30-day and evidence-ledger diagnostics, locked untouched future days, backward Revisit routing, 95%-threshold command evidence, optional-visual semantics, and desktop/mobile fit.",
      "Controlled Geography pilot entry now exposes one unlocked start or resume action only after approval and roster check-in. Paused, unapproved, and unchecked states expose no lesson or optional-visual bypass; blocker feedback pauses navigation immediately and reviewed blockers resume cleanly.",
      "Adaptive-teacher transition verifier now proves browser-side timeout recovery after a deliberately stalled request while preserving the local repair route.",
      "Student dashboard verifier now proves the real Exit action clears the learner profile, Geography progress, authenticated account marker, and localhost preview token together.",
      "UPSC intake self-study verifier proves the three preparation-history choices, folded optional tuning, Intermediate diagnosis-first route, four-signal dashboard, and desktop/mobile fit.",
      "Level-aware guided-session verifier now also proves legacy-profile normalization before routing.",
      "Self-study intake verifier now proves one explicit preparation-history answer is required before path generation, while daily duration and study preferences remain folded as optional tuning.",
      "Level-aware guided-session verifier now proves the Beginner Watch surface removes the redundant route-summary panel and expands the player to a 616px desktop lesson surface without mobile overflow.",
      "Geography Watch-simple verifier now proves a cleared Beginner direct Watch revisit hides the player and opens MCQ practice.",
      "Geography Talk-simple verifier proves no raw learner-visible route-stage label, one repair follow-up, direct MCQ clearance at 96%, persisted teacher trace, desktop fit, and mobile fit.",
      "Guarded clean-output Webpack production rebuild passes 90 routes; the post-build route matrix passes 89/89 concrete pages without missing client chunks.",
      "Day 2 Universe-to-Earth static verifier passes 21 checks, while its browser rehearsal proves all five visual stages, the Talk handoff, desktop/mobile fit, and zero browser errors.",
      "Animation-studio regression proves the compact Day 2 learner visual stays available without exposing the operator-heavy studio link, while the direct master studio retains its deep storyboard catalog on desktop and mobile.",
      "Day 3 interior-to-plates static verifier passes 20 checks, while its browser rehearsal proves all five visual stages, learner-visible mantle-current motion, Watch-to-Talk handoff, optional Earth Layers proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 4 geomorphic-process static verifier passes 19 checks, while its browser rehearsal proves all five visual stages, Watch-to-Talk handoff, optional Disaster Link proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 5 climatology-base static verifier passes 19 checks, while its browser rehearsal proves all five visual stages, Watch-to-Talk handoff, optional Monsoon Simulator proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 6 ocean-system static verifier passes 19 checks, while its browser rehearsal proves all five visual stages, Watch-to-Talk handoff, optional Monsoon Simulator proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 7 physical-geography-consolidation static verifier passes 19 checks, while its browser rehearsal proves all five integration stages, Watch-to-Talk handoff, optional Earth Layers proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 8 India-physiography static verifier passes 19 checks, while its browser rehearsal proves all five relief-map stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 9 Indian-drainage static verifier passes 19 checks, while its browser rehearsal proves all five river-map stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 10 Indian-monsoon static verifier passes 19 checks, while its browser rehearsal proves all five monsoon-sequence stages, Watch-to-Talk handoff, optional Monsoon Simulator proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 11 India-climate-regions static verifier passes 19 checks, while its browser rehearsal proves all five regional-comparison stages, Watch-to-Talk handoff, optional Monsoon Simulator proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 12 soils-and-vegetation static verifier passes 19 checks, while its browser rehearsal proves all five geography-environment bridge stages, Watch-to-Talk handoff, optional Environment Bridge proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 13 resources-and-agriculture static verifier passes 19 checks, while its browser rehearsal proves all five India location-logic stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 14 India-map-drill static verifier passes 19 checks, while its browser rehearsal proves all five Week 2 consolidation stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 15 population-geography static verifier passes 19 checks, while its browser rehearsal proves all five human-geography launch stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 16 settlements static verifier passes 19 checks, while its browser rehearsal proves all five settlement-classification stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 17 economic-activities static verifier passes 19 checks, while its browser rehearsal proves all five sector-transition stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 18 transport-and-trade static verifier passes 19 checks, while its browser rehearsal proves all five connectivity stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 19 industry-location static verifier passes 19 checks, while its browser rehearsal proves all five location-factor stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 20 regional-development static verifier passes 19 checks, while its browser rehearsal proves all five disparity-and-planning stages, Watch-to-Talk handoff, optional Environment Bridge proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 21 human-geography-consolidation static verifier passes 19 checks, while its browser rehearsal proves all five integration-and-repair stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 22 atlas-mastery static verifier passes 19 checks, while its browser rehearsal proves all five map-recall stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 23 PYQ-pattern-reading static verifier passes 19 checks, while its browser rehearsal proves all five trap-reading stages, Watch-to-Talk handoff, optional MCQ Engine proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 24 disaster-geography-bridge static verifier passes 19 checks, while its browser rehearsal proves all five hazard-to-risk stages, Watch-to-Talk handoff, optional Disaster Link proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 25 environment-geography-bridge static verifier passes 19 checks, while its browser rehearsal proves all five biome-to-conservation stages, Watch-to-Talk handoff, optional Environment Bridge proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 26 mains-geography-application static verifier passes 19 checks, while its browser rehearsal proves all five answer-writing stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 27 full-geography-drill static verifier passes 19 checks, while its browser rehearsal proves all five integrated-revision stages, Watch-to-Talk handoff, optional MCQ Engine proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 28 weak-area-repair static verifier passes 19 checks, while its browser rehearsal proves all five targeted-recovery stages, Watch-to-Talk handoff, optional MCQ Engine proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 29 final-mock-review static verifier passes 19 checks, while its browser rehearsal proves all five mock-analysis stages, Watch-to-Talk handoff, optional MCQ Engine proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
      "Day 30 geography-command-day static verifier passes 19 checks, while its browser rehearsal proves all five command-closeout stages, Watch-to-Talk handoff, optional India Interactive Map proof persistence, MCQ handoff, mobile fit, and zero browser errors.",
    ],
  },
];

export const may31Plan: DailyLaunchPlan = {
  date: "May 31, 2026",
  title: "Live Student Boundary Closure",
  objective:
    "Keep the Geography pilot honest: finish local security hardening, then apply the live Supabase and OAuth configuration before any public invite.",
  completionTarget: "No public invite until live identity and cross-session learner-state recovery pass.",
  checkpoints: [
    {
      title: "Student-visible route isolation",
      owner: "Platform",
      status: "done",
      percent: 100,
      outcome: "Learners see the simple UPSC path while operator, audit, admin, simulation, and legacy exam routes redirect to Today.",
    },
    {
      title: "Internal API access hardening",
      owner: "Security",
      status: "done",
      percent: 100,
      outcome: "Audit APIs validate Supabase sessions, reject forged JWTs, and allow explicit localhost master tokens only for local verification.",
    },
    {
      title: "Protected Vercel preview",
      owner: "Platform",
      status: "done",
      percent: 100,
      outcome: "Linked the workspace to upsc-command, configured browser-safe Supabase variables, built the current 90-route preview, and verified protected edge responses without changing the production alias.",
    },
    {
      title: "Supabase live migration",
      owner: "Backend",
      status: "pending",
      percent: 0,
      outcome: "Apply the learner profile and subject progress RLS migration in the live Supabase SQL Editor.",
    },
    {
      title: "Distributed AI limiter apply",
      owner: "Backend",
      status: "pending",
      percent: 0,
      outcome: "Apply the adaptive-teacher limiter migration and configure the server-only SUPABASE_SECRET_KEY in Vercel.",
    },
    {
      title: "Google OAuth continuity rehearsal",
      owner: "Launch QA",
      status: "pending",
      percent: 0,
      outcome: "Verify Google login and same-account profile/progress recovery in a second browser profile on the deployed URL.",
    },
    {
      title: "Real Geography Day 1 pack",
      owner: "Content",
      status: "risk",
      percent: 74,
      outcome: "Source-backed portal-native Day 1 foundation lesson, India map-relationship drill, Day 2 Universe-to-Earth visual, and Day 3 interior-to-plates bridge pass locally. Attach the final recorded lecture, transcript approval, detailed visual production, and fresh advanced MCQ set.",
    },
  ],
};

export const may24Plan: DailyLaunchPlan = {
  date: "May 24, 2026",
  title: "Geography Production Pilot Closure",
  objective:
    "Make Geography reliable enough for internal/founder testing and prepare the student testing link path.",
  completionTarget: "Geography 95-98% functional locally, with remaining gaps clearly listed.",
  checkpoints: [
    {
      title: "Admin launch tracker",
      owner: "Platform",
      status: "done",
      percent: 100,
      outcome: "Admin can see day-wise work log, May 24/25 plan, next six-day focus, and launch risk.",
    },
    {
      title: "Geography Watch room",
      owner: "Learning loop",
      status: "done",
      percent: 96,
      outcome: "Each day opens a credible lecture scene with topic, duration, learning promise, and visible Watch-to-Talk handoff.",
    },
    {
      title: "Geography Talk room",
      owner: "AI discussion",
      status: "done",
      percent: 96,
      outcome: "Student recall loop asks, evaluates, scores, routes a cleared learner directly to MCQ, and keeps Revisit available only when repair is required.",
    },
    {
      title: "Geography Visual Lab",
      owner: "Map and concept lab",
      status: "done",
      percent: 95,
      outcome: "Earth layer, monsoon, India atlas, rivers, parks, sanctuaries, soil-climate, optional India-map support, and Lab-to-MCQ handoff are browser-verified without blocking a cleared learner.",
    },
    {
      title: "MCQ fresh upload readiness",
      owner: "Admin content",
      status: "done",
      percent: 100,
      outcome: "Contextual upload, strict Geography audit, 25-question GEO-D01 launch-bank rule, visible quality score, and local practice unlock are ready for fresh advanced MCQs.",
    },
    {
      title: "Student test smoke",
      owner: "Launch QA",
      status: "done",
      percent: 98,
      outcome: "The shareable Geography Day 1 pilot exposes exactly Learn, Discuss, and MCQ; 96/100 discussion clearance routes directly to MCQ, optional India-map support stays available, and desktop/mobile fit passes.",
    },
  ],
};

export const may25Plan: DailyLaunchPlan = {
  date: "May 25, 2026",
  title: "Controlled Student Testing Readiness",
  objective:
    "Prepare one clean Geography testing link and one admin observation workflow before inviting students.",
  completionTarget: "One subject stable for controlled student testing, with known limitations documented.",
  checkpoints: [
    {
      title: "Founder review pass",
      owner: "Admin",
      status: "in-progress",
      percent: 70,
      outcome: "Admin release decision and 7-point founder checklist exist locally; founder still needs to perform the human review before sharing with students.",
    },
    {
      title: "Student testing route",
      owner: "Platform",
      status: "done",
      percent: 100,
      outcome: "Controlled local Geography student route exists at /upsc/geography/pilot with dynamic current action, first-tester script, session guide, blocker pause state, non-clickable paused path cards, zero-progress start proof, Day 1 path, gate checklist, and no admin-facing controls.",
    },
    {
      title: "Content placeholder discipline",
      owner: "Learning content",
      status: "done",
      percent: 98,
      outcome: "Geography Days 1-30 have staged local class packs and other subjects still show planned placeholders instead of broken empty states.",
    },
    {
      title: "Admin observation board",
      owner: "Operations",
      status: "done",
      percent: 99,
      outcome: "Admin launch plan now shows the testing link, feedback counts, latest observations, review action, founder checklist, approve/pause release decision, final student share packet, and live blocker stop-sharing override.",
    },
    {
      title: "Student feedback capture",
      owner: "QA",
      status: "done",
      percent: 99,
      outcome: "Student pilot captures tester feedback, immediately pauses itself on self-reported or existing Blocker feedback, resumes through local admin review events, and shows the finish-feedback rule before the pilot is closed.",
    },
  ],
};

export const nextSixDayFocus: SixDayFocus[] = [
  {
    date: "May 31",
    focus: "Live database handoff",
    output: "Apply the Supabase learner-state migration and verify RLS tables and policies.",
    riskControl: "Do not invite students until the post-migration SQL check passes.",
  },
  {
    date: "June 1",
    focus: "OAuth continuity",
    output: "Verify Google login and same-account progress recovery in a second browser profile.",
    riskControl: "Do not accept local preview behavior as proof of live continuity.",
  },
  {
    date: "June 2",
    focus: "Real Day 1 content",
    output: "Attach the final Geography lecture, transcript, visual proof, and fresh advanced MCQs.",
    riskControl: "Keep practice locked until the fresh MCQ quality gate passes.",
  },
  {
    date: "June 3",
    focus: "Controlled tester wave",
    output: "Invite up to three students and capture one feedback receipt per tester.",
    riskControl: "Pause sharing immediately when any blocker is reported.",
  },
  {
    date: "June 4",
    focus: "Feedback repair",
    output: "Resolve every first-wave confusion point and replay the same Geography path.",
    riskControl: "Do not widen the tester group while blocker feedback remains open.",
  },
  {
    date: "June 5-6",
    focus: "Geography expansion",
    output: "Stabilize the remaining Geography class packs before Environment work resumes.",
    riskControl: "No superficial subject expansion before the Geography live loop is proven.",
  },
];

export const launchFocusAreas: DeliveryFocusItem[] = [
  {
    title: "One subject first",
    owner: "Product strategy",
    status: "in-progress",
    percent: 86,
    outcome: "Geography remains the production pilot. The local loop passes, but live identity continuity and the final Day 1 content pack must close before Environment expansion.",
  },
  {
      title: "Learning loop depth",
      owner: "Student experience",
      status: "in-progress",
      percent: 95,
      outcome: "Learn, Discuss, and MCQ pass as the three-step learner path. Watch now presents one player-level completion action with no visible day jumping or premature skip action, and approved recording completion hands off directly to Talk. The optional command-room and Track maps lock future unfinished days while preserving completed or evidence-bearing review. Visual Lab can return directly to MCQ without a forced proof save, while Revisit and Track stay connected without competing with the next action. Real media depth and first-student friction evidence remain open.",
  },
    {
      title: "Admin accountability",
      owner: "Operations",
      status: "in-progress",
      percent: 93,
      outcome: "Daily plan, completion, next work, security boundary, testing feedback, founder checklist, pilot release decision, and share packet are visible. Live Supabase and OAuth results still need to be recorded after dashboard application.",
  },
  {
    title: "Fresh content quality",
    owner: "Content",
    status: "risk",
    percent: 35,
    outcome: "The quality gate, schedule scaffolds, and founder-corpus Day 1 intake map exist. The final student-grade Day 1 media, visual depth, and fresh advanced MCQ bank still need delivery.",
  },
];

export const immediateLaunchActions: DeliveryFocusItem[] = [
  {
    title: "Apply Supabase learner-state migration",
    owner: "Backend / Admin",
    status: "pending",
    percent: 0,
    outcome:
      "Run the included SQL migration, then confirm both learner tables and their auth.uid()-bound RLS policies with the read-only verification query.",
  },
  {
    title: "Verify Google OAuth and continuity",
    owner: "Launch QA",
    status: "pending",
    percent: 0,
    outcome:
      "Use the deployed URL and two browser profiles to prove the same Google account restores its profile and Geography progress while a different account remains isolated.",
  },
  {
    title: "Load real Geography Day 1 assets",
    owner: "Content",
    status: "risk",
    percent: 35,
    outcome:
      "The Day 1 and Day 2 split is implemented locally. Attach the final Day 1 lecture, transcript approval, detailed visual production, and fresh student-grade MCQs using the prepared founder-corpus intake map.",
  },
  {
    title: "Invite the first tiny tester group",
    owner: "Launch QA",
    status: "pending",
    percent: 0,
    outcome:
      "Only after live continuity and Day 1 content pass, share /upsc/geography/pilot with up to three students and require one feedback receipt each.",
  },
];

export const liveReleaseBoundary: LiveReleaseGate[] = [
  {
    step: 1,
    title: "Apply learner-state RLS",
    status: "pending",
    controlPlane: "Supabase SQL Editor",
    operatorAction:
      "Run supabase/migrations/20260531_upsc_learner_state.sql, then run supabase/verify/20260531_upsc_learner_state_checks.sql.",
    proofReceipt: "Both learner tables exist, RLS is enabled, and auth.uid()-bound policies pass the read-only verification query.",
  },
  {
    step: 2,
    title: "Apply the distributed Talk limiter",
    status: "pending",
    controlPlane: "Supabase SQL Editor and Vercel Environment Variables",
    operatorAction:
      "Run supabase/migrations/20260531_upsc_adaptive_teacher_rate_limit.sql, verify it, and add SUPABASE_SECRET_KEY as a server-only Vercel secret.",
    proofReceipt: "The restricted RPC verification passes and the browser bundle contains no sb_secret_ backend key.",
  },
  {
    step: 3,
    title: "Activate the live AI teacher",
    status: "pending",
    controlPlane: "Vercel Environment Variables",
    operatorAction:
      "Add GEMINI_API_KEY as a server-only secret, deploy a preview, and evaluate a real authenticated Talk request before production AI language is used.",
    proofReceipt: "A real learner Talk response reports providerConfigured true without exposing the key to the browser.",
  },
  {
    step: 4,
    title: "Prove deployed Google login continuity",
    status: "pending",
    controlPlane: "Supabase Auth, Vercel preview, and two browser profiles",
    operatorAction:
      "Confirm the deployed OAuth callback, then sign in with the same Google account in a second browser profile and verify Geography progress recovery.",
    proofReceipt: "The same account restores its profile and progress while a different account remains isolated.",
  },
  {
    step: 5,
    title: "Load the real Day 1 release pack",
    status: "risk",
    controlPlane: "Content Command and MCQ Upload",
    operatorAction:
      "Attach the approved lecture and transcript pair, finish the detailed visual proof, and upload the fresh student-grade MCQ set through the prepared intake gate.",
    proofReceipt: "Approved media opens honestly, the transcript is present, and fresh MCQs pass the strict Geography quality gate.",
  },
  {
    step: 6,
    title: "Run the controlled first wave",
    status: "pending",
    controlPlane: "Launch Tracker",
    operatorAction:
      "Invite no more than three checked-in testers through /upsc/geography/pilot and pause immediately when a blocker is reported.",
    proofReceipt: "Each tester leaves one feedback receipt and every blocker is reviewed before the second wave is unlocked.",
  },
];
