import {
  BrainCircuit,
  ClipboardCheck,
  Compass,
  Earth,
  LineChart,
  LucideIcon,
  Map,
  Mountain,
  Orbit,
  PlayCircle,
  RefreshCcw,
  Route,
  ShieldAlert,
  Sprout,
  Target,
  Waves,
} from "lucide-react";

export type LearningStep = {
  label: string;
  detail: string;
  icon: LucideIcon;
  tone: string;
};

export type GeographySession = {
  day: number;
  week: number;
  title: string;
  chapter: string;
  anchor: string;
  duration: string;
  watch: string;
  talk: string;
  test: string;
  track: string;
  revisit: string;
  lab: string;
  gsCompatibility?: string;
  subtopics?: string[];
};

export const learningSteps: LearningStep[] = [
  {
    label: "Talk",
    detail: "Recall-first AI discussion",
    icon: BrainCircuit,
    tone: "bg-teal-50 text-teal-800 ring-teal-100",
  },
  {
    label: "Watch",
    detail: "Gap-repair concept session",
    icon: PlayCircle,
    tone: "bg-emerald-50 text-emerald-800 ring-emerald-100",
  },
  {
    label: "Test",
    detail: "MCQ and mains practice action",
    icon: ClipboardCheck,
    tone: "bg-amber-50 text-amber-800 ring-amber-100",
  },
  {
    label: "Track",
    detail: "Gap, confidence, and recall map",
    icon: LineChart,
    tone: "bg-slate-50 text-slate-800 ring-slate-200",
  },
  {
    label: "Revisit",
    detail: "Revision queue and weak-topic repair",
    icon: RefreshCcw,
    tone: "bg-stone-50 text-stone-800 ring-stone-200",
  },
];

export const upscCalendar = [
  {
    window: "Daily",
    title: "UPSC Daily Mission Control",
    detail: "Student launcher for the selected subject day, Watch, Talk, Lab, MCQ, Track, and Revisit.",
    status: "Structure ready",
    href: "/upsc/daily-command",
  },
  {
    window: "Product",
    title: "UPSC Yearly Planner",
    detail: "Pricing, yearly subject sequence, GS coverage layers, PYQ preload target, and three-day launch plan.",
    status: "Structure ready",
    href: "/upsc/yearly-planner",
  },
  {
    window: "Pricing",
    title: "UPSC Pricing Command",
    detail: "Rs 399 monthly base with yearly, 18-month, and three-year discount ladders for launch enrollment.",
    status: "Structure ready",
    href: "/upsc/pricing",
  },
  {
    window: "Optional",
    title: "Optional Subject Command",
    detail: "Paper I and Paper II page shell for every UPSC optional subject with syllabus and PYQ preload targets.",
    status: "Structure ready",
    href: "/upsc/optional-subjects",
  },
  {
    window: "Sources",
    title: "Syllabus and PYQ Library",
    detail: "Official source anchors, GS syllabus nodes, prelims/mains PYQ import rows, and optional Paper I/II ledger.",
    status: "Structure ready",
    href: "/upsc/source-library",
  },
  {
    window: "Current Affairs",
    title: "Covered-Topic Current Affairs",
    detail: "Subject news hooks unlock only after the linked static topic is covered by the student.",
    status: "Structure ready",
    href: "/upsc/current-affairs",
  },
  {
    window: "June",
    title: "Geography",
    detail: "First complete subject sprint with map-first learning.",
    status: "Build now",
    href: "/upsc/geography",
  },
  {
    window: "July 1-20",
    title: "Environment",
    detail: "Ecology, biodiversity, climate, conventions, current affairs.",
    status: "Structure ready",
    href: "/upsc/environment",
  },
  {
    window: "July 21-31",
    title: "Disaster Management",
    detail: "Risk, preparedness, institutions, case studies, answer writing.",
    status: "Structure ready",
    href: "/upsc/disaster-management",
  },
  {
    window: "August",
    title: "Economy",
    detail: "Core economy with budget, schemes, banking, inflation, growth.",
    status: "Structure ready",
    href: "/upsc/economy",
  },
  {
    window: "September",
    title: "Science and Tech",
    detail: "Applied science, emerging tech, space, biotech, defence tech.",
    status: "Structure ready",
    href: "/upsc/science-tech",
  },
  {
    window: "October",
    title: "Polity and Governance",
    detail: "Constitutional command plus governance application.",
    status: "Structure ready",
    href: "/upsc/polity-governance",
  },
  {
    window: "November",
    title: "Internal Security and Indian Society",
    detail: "Security frameworks, social change, vulnerable sections.",
    status: "Structure ready",
    href: "/upsc/internal-security-society",
  },
  {
    window: "December-January",
    title: "History",
    detail: "Modern, Ancient, Medieval, Art and Culture in four 15-day blocks.",
    status: "Structure ready",
    href: "/upsc/history",
  },
  {
    window: "Revision Phase",
    title: "All-Subject Revision Command",
    detail: "Global revisit queue, subject trackers, and command readiness across the full UPSC plan.",
    status: "Structure ready",
    href: "/upsc/revision-command",
  },
  {
    window: "Question Engine",
    title: "UPSC MCQ Command Center",
    detail: "Fresh MCQ batch planning, CSV contracts, upload links, and day-wise readiness.",
    status: "Structure ready",
    href: "/upsc/mcq-command",
  },
  {
    window: "Practice",
    title: "Custom MCQ Question Bank",
    detail: "Student practice builder selects easy, medium, hard, or PYQ-style questions from recall, consistency, and marks.",
    status: "Structure ready",
    href: "/upsc/question-bank",
  },
  {
    window: "Content Engine",
    title: "UPSC Content Command Center",
    detail: "Video, notes, transcript, source type, and Watch-room readiness across all class days.",
    status: "Structure ready",
    href: "/upsc/content-command",
  },
  {
    window: "Audit",
    title: "UPSC Readiness Audit Center",
    detail: "Local launch report for routes, subjects, content, MCQs, progress, and pending data work.",
    status: "Structure ready",
    href: "/upsc/readiness-audit",
  },
];

export const geographyWeeks = [
  {
    week: "Week 1",
    title: "Physical Geography Foundation",
    detail: "Universe, Earth origin, interior, tectonics, landforms, atmosphere, ocean, and monsoon.",
    icon: Earth,
  },
  {
    week: "Week 2",
    title: "India Map Command",
    detail: "Physiography, drainage, soils, vegetation, agriculture, minerals, energy, industry, and transport.",
    icon: Map,
  },
  {
    week: "Week 3",
    title: "World, Human, and Political Geography",
    detail: "World map systems, human geography, India borders, Northeast, tribal geography, and news geography.",
    icon: Route,
  },
  {
    week: "Week 4",
    title: "Integrated Recall and Command",
    detail: "Full-syllabus recall, weak-area repair, PYQ traps, mock practice, and final Geography command.",
    icon: Target,
  },
];

export const geographyLabs = [
  {
    slug: "universe",
    title: "Universe Foundation Visual",
    detail: "Expansion, gravity, solar-disk accretion, differentiation, atmosphere and hydrosphere.",
    icon: Orbit,
  },
  {
    slug: "earth-layers",
    title: "Earth Layers Lab",
    detail: "Interior structure, plates, boundaries, earthquakes.",
    icon: Mountain,
  },
  {
    slug: "monsoon",
    title: "Monsoon Simulator",
    detail: "Pressure, winds, ITCZ movement, orographic rainfall.",
    icon: Waves,
  },
  {
    slug: "india-map",
    title: "India Interactive Map",
    detail: "Rivers, soils, vegetation, minerals, crops, climate zones.",
    icon: Compass,
  },
  {
    slug: "disaster-link",
    title: "Disaster Link",
    detail: "Floods, cyclones, landslides, droughts, mitigation logic.",
    icon: ShieldAlert,
  },
  {
    slug: "environment-bridge",
    title: "Environment Bridge",
    detail: "Biomes, climate change, biodiversity, conservation geography.",
    icon: Sprout,
  },
  {
    slug: "mcq-engine",
    title: "MCQ Engine",
    detail: "Fresh question upload, chapter test, daily mixed drill.",
    icon: ClipboardCheck,
  },
];

export const geographySessions: GeographySession[] = [
  {
    day: 1,
    week: 1,
    title: "Geographic Thinking and Map Relationships",
    chapter: "Geography Foundation",
    anchor: "What, where, why; absolute and relative location; site and situation; scale; India relationship drills",
    duration: "12 min",
    watch: "Learn how geography asks why here and not there, then use location, scale, site, situation, and map relationships to read India spatially.",
    talk: "Why is asking why here and not there more useful than memorizing isolated locations? Explain with one India map relationship.",
    test: "Fresh MCQ slot: geographic lens, absolute-relative location, site-situation, scale, and India relationship drills.",
    track: "Mark whether you can explain one location through relationship, scale, and an India map cue.",
    revisit: "Rebuild one India map relationship using what, where, why, site, situation, and scale.",
    lab: "India Interactive Map",
    gsCompatibility:
      "GS Paper I Geography foundation: spatial distribution, location logic, physical-human relationships, and applied India map reading.",
    subtopics: [
      "what, where, and why",
      "absolute and relative location",
      "site and situation",
      "geographic scale",
      "India map relationships",
    ],
  },
  {
    day: 2,
    week: 1,
    title: "Universe, Solar System, and Origin of Earth",
    chapter: "Physical Geography Foundation",
    anchor: "Big Bang, expansion of space, CMB, redshift, galaxies, solar nebula, accretion, differentiation, atmosphere, hydrosphere",
    duration: "12 min",
    watch: "Study the Universe sample module as short slides, then connect cosmic evidence with Earth formation and habitability.",
    talk: "Explain the Universe-to-Earth chain: Big Bang evidence, expanding space, solar nebula, accretion, differentiation, and one UPSC trap.",
    test: "Fresh MCQ slot: Big Bang evidence, redshift, CMB, solar nebula, accretion, differentiation, atmosphere and hydrosphere.",
    track: "Separate the causal sequence from disconnected universe facts and examiner traps.",
    revisit: "Speak the eight-step chain: expansion, evidence, gravity, solar nebula, accretion, differentiation, atmosphere, hydrosphere.",
    lab: "Universe Foundation Visual",
    gsCompatibility:
      "GS Paper I Physical Geography foundation: origin of the universe, solar-system formation, evolution of Earth, differentiation, atmosphere, hydrosphere, and statement-trap logic.",
    subtopics: [
      "Big Bang and expanding space",
      "CMB and redshift evidence",
      "galaxies and solar system",
      "expansion of space",
      "cooling and gravity",
      "solar nebula and accretion",
      "Earth differentiation",
      "atmosphere and hydrosphere",
    ],
  },
  {
    day: 3,
    week: 1,
    title: "Interior of Earth, Seismology, and Plate Movement",
    chapter: "Physical Geography Foundation",
    anchor: "Interior of Earth, seismic waves, crust, mantle, core, lithosphere, asthenosphere, convection, plate boundaries",
    duration: "12 min",
    watch: "Use seismic evidence to read Earth layers, then connect mantle behavior with moving plates and hazard patterns.",
    talk: "How do seismic waves and mantle dynamics explain why earthquakes, volcanoes, and mountains are not randomly distributed?",
    test: "Fresh MCQ slot: Earth layers, seismic evidence, convection and plate boundaries.",
    track: "Map weak links between layers, wave behavior, convection and boundary types.",
    revisit: "Redraw Earth layers, then compare convergent, divergent, and transform boundaries.",
    lab: "Earth Layers Lab",
  },
  {
    day: 4,
    week: 1,
    title: "Volcanoes, Rocks, and Geomorphic Processes",
    chapter: "Physical Geography Foundation",
    anchor: "Volcanoes, rocks and rock cycle, weathering, mass wasting, erosion, deposition, landform development",
    duration: "12 min",
    watch: "Understand internal and external forces shaping landforms.",
    talk: "Why does the same rock produce different landforms in different climates?",
    test: "Fresh MCQ slot: volcanoes, rocks, rock cycle, geomorphic agents and processes.",
    track: "Tag confusion between process and landform.",
    revisit: "Make one table of agent, process, and resulting landform.",
    lab: "Disaster Link",
  },
  {
    day: 5,
    week: 1,
    title: "Atmosphere, Insolation, Pressure, and Winds",
    chapter: "Physical Geography Foundation",
    anchor: "Atmosphere composition and structure, insolation, heat budget, temperature distribution, pressure belts, winds, jet streams, local winds",
    duration: "12 min",
    watch: "Build pressure and wind logic from unequal heating.",
    talk: "Why does air move, and why does it curve?",
    test: "Fresh MCQ slot: pressure belts and wind systems.",
    track: "Check if Coriolis, pressure gradient, and belts are conceptually clear.",
    revisit: "Sketch global pressure belts without notes.",
    lab: "Monsoon Simulator",
  },
  {
    day: 6,
    week: 1,
    title: "Humidity, Cyclones, Climate Types, and Ocean System",
    chapter: "Physical Geography Foundation",
    anchor: "Humidity, precipitation, air masses, fronts, cyclones, anticyclones, climate classification, ocean floor, salinity, temperature, currents, tides",
    duration: "12 min",
    watch: "Relate ocean currents with climate and coastal effects.",
    talk: "How do moisture, pressure systems, climate classification, and ocean currents connect rainfall, deserts, fog, storms, and fisheries?",
    test: "Fresh MCQ slot: precipitation, fronts, cyclones, ocean currents, tides, and salinity.",
    track: "Mark cyclone, climate, and current-location pairs for map revision.",
    revisit: "Trace warm/cold currents and one cyclone pathway on a blank world map.",
    lab: "Monsoon Simulator",
  },
  {
    day: 7,
    week: 1,
    title: "Indian Monsoon, ENSO-IOD-MJO, and Maritime Zones",
    chapter: "Physical Geography Foundation",
    anchor: "Indian monsoon, El Nino, La Nina, IOD, MJO, EEZ, continental shelf, maritime zones, physical integration",
    duration: "12 min",
    watch: "Build monsoon as a moving pressure-wind-ocean system, then add climate oscillations and maritime-zone traps.",
    talk: "Why is the monsoon powerful but unreliable, and how do ENSO, IOD, MJO, and maritime zones create UPSC traps?",
    test: "Fresh MCQ slot: monsoon mechanism, ENSO-IOD-MJO, EEZ, continental shelf, maritime zones.",
    track: "Generate the first physical geography weak-topic list.",
    revisit: "Reattempt weak concepts from Days 1-6 before opening India map command.",
    lab: "Monsoon Simulator",
  },
  {
    day: 8,
    week: 2,
    title: "India Physiography",
    chapter: "India Map Command",
    anchor: "Himalayas, plains, plateau, desert, coast, islands",
    duration: "12 min",
    watch: "Build India relief as a map-first framework.",
    talk: "How does relief control rivers, climate, soils, agriculture, and risk?",
    test: "Fresh MCQ slot: physiographic divisions.",
    track: "Map blank zones where recall is weak.",
    revisit: "Draw India physiographic divisions from memory.",
    lab: "India Interactive Map",
  },
  {
    day: 9,
    week: 2,
    title: "Indian Drainage, Lakes, and Wetlands",
    chapter: "India Map Command",
    anchor: "Drainage overview, Indus, Ganga, Brahmaputra, east-flowing and west-flowing peninsular rivers, lakes, wetlands, Ramsar sites",
    duration: "12 min",
    watch: "Understand drainage through slope, origin, and basin behavior.",
    talk: "Why do Himalayan and peninsular rivers behave differently?",
    test: "Fresh MCQ slot: rivers and tributaries.",
    track: "Tag river-origin, tributary, and state-location errors.",
    revisit: "Trace major rivers and tributaries on a blank map.",
    lab: "India Interactive Map",
  },
  {
    day: 10,
    week: 2,
    title: "Soils, Natural Vegetation, and Forest Policy",
    chapter: "India Map Command",
    anchor: "Soil classification, soil erosion, degradation, forest types, forest cover, conservation, forest policy",
    duration: "12 min",
    watch: "Connect soils and vegetation with climate, parent rock, relief, water, use, and conservation policy.",
    talk: "Why do soil and vegetation questions often test geography plus environment, and where do UPSC traps appear?",
    test: "Fresh MCQ slot: soils, erosion, forest types, forest cover and policy.",
    track: "Tag soil-location-crop and forest-climate confusion.",
    revisit: "Match soil, region, crop, limitation, vegetation, and conservation rule.",
    lab: "Environment Bridge",
  },
  {
    day: 11,
    week: 2,
    title: "Indian Agriculture",
    chapter: "India Map Command",
    anchor: "Cropping seasons, major crops, top producing states, agricultural revolutions, irrigation, food security, agricultural policy, agricultural issues",
    duration: "12 min",
    watch: "Connect crops and irrigation with rainfall, soils, relief, markets, policy, and food security.",
    talk: "Why do crops cluster where they do, and how do irrigation and food-security policy change the geography?",
    test: "Fresh MCQ slot: cropping seasons, crops/states, revolutions, irrigation, food security, agricultural issues.",
    track: "Map crop belts, irrigation logic, and policy-linked weak areas.",
    revisit: "Build one crop-soil-rainfall-state-policy grid.",
    lab: "India Interactive Map",
  },
  {
    day: 12,
    week: 2,
    title: "Minerals, Energy, Industries, and Economic Geography",
    chapter: "India Map Command",
    anchor: "Ferrous, non-ferrous and critical minerals, energy resources, iron and steel, textile industry, industrial corridors",
    duration: "12 min",
    watch: "Connect minerals, energy, and industries with raw material, power, transport, market, policy, and strategic supply chains.",
    talk: "Why do minerals, energy resources, and industries cluster where they do, and what changes with critical minerals?",
    test: "Fresh MCQ slot: minerals, energy, steel, textile, corridors, and location factors.",
    track: "Map resource belts, energy regions, and industry-location traps.",
    revisit: "Compare iron-steel, textile, energy, and critical-mineral location logic.",
    lab: "India Interactive Map",
  },
  {
    day: 13,
    week: 2,
    title: "Transport and Communications",
    chapter: "India Map Command",
    anchor: "Ports and maritime trade, road transport, railway transport, inland waterways, communication corridors",
    duration: "12 min",
    watch: "Study connectivity as a geographic and economic force linking ports, roads, railways, waterways, markets, and regions.",
    talk: "Why do corridors, ports, roads, railways, and inland waterways transform regions differently?",
    test: "Fresh MCQ slot: ports, maritime trade, roads, railways, inland waterways, corridors.",
    track: "Map corridor, port, railway, and waterway recall.",
    revisit: "Trace major transport corridors and port-waterway logic.",
    lab: "India Interactive Map",
  },
  {
    day: 14,
    week: 3,
    title: "World Physical Geography and Map Systems",
    chapter: "World, Human, and Political Geography",
    anchor: "World physiography, world rivers, world lakes, straits and channels, world biomes",
    duration: "12 min",
    watch: "Convert world map facts into cause-location relationships across relief, rivers, lakes, straits, channels, and biomes.",
    talk: "How can a world map fact become a concept question instead of isolated atlas memory?",
    test: "Fresh MCQ slot: world physiography, rivers, lakes, straits, channels, biomes.",
    track: "Generate world map weak areas.",
    revisit: "Repair the weakest five world map locations and biome-climate links.",
    lab: "India Interactive Map",
  },
  {
    day: 15,
    week: 3,
    title: "Human Geography",
    chapter: "Human and Economic Geography",
    anchor: "Population geography, migration geography, urban geography, cultural geography",
    duration: "12 min",
    watch: "Study population, migration, urbanization, and culture through resources, economy, risk, networks, and identity.",
    talk: "Why do people cluster, migrate, urbanize, and form cultural regions in some places and not others?",
    test: "Fresh MCQ slot: population, migration, urban, and cultural geography.",
    track: "Mark concept gaps in density, growth, migration, urbanization, and cultural regions.",
    revisit: "Compare density, distribution, demographic transition, migration push-pull, and urban hierarchy.",
    lab: "India Interactive Map",
  },
  {
    day: 16,
    week: 3,
    title: "Indian Political Geography",
    chapter: "World, Human, and Political Geography",
    anchor: "India's borders, Northeast India, tribal geography, strategic regions, political map logic",
    duration: "12 min",
    watch: "Build India's borders, Northeast, and tribal regions through terrain, identity, connectivity, security, and administrative logic.",
    talk: "Why do border, Northeast, and tribal geography questions require political, physical, and human geography together?",
    test: "Fresh MCQ slot: borders, Northeast, tribal geography, and strategic regional logic.",
    track: "Separate map recall errors from political-geography reasoning gaps.",
    revisit: "Map one border region, one Northeast corridor, and one tribal-geography trap.",
    lab: "India Interactive Map",
  },
  {
    day: 17,
    week: 3,
    title: "Current Affairs Geography",
    chapter: "World, Human, and Political Geography",
    anchor: "Geopolitical geography in news, connectivity and infrastructure geography, climate change geography, recent disaster geography",
    duration: "12 min",
    watch: "Attach current news to static geography: geopolitics, connectivity, climate change, disasters, infrastructure, and map-linked policy.",
    talk: "How should a covered Geography topic unlock a current-affairs hook without turning into random news reading?",
    test: "Fresh MCQ slot: geopolitics, connectivity, climate change, disaster events, and static-current linkages.",
    track: "Mark news hooks that are unlocked by covered static topics.",
    revisit: "Turn one current event into cause, location, impact, institution, and UPSC trap.",
    lab: "India Interactive Map",
  },
  {
    day: 18,
    week: 4,
    title: "Integrated Physical and India Map Recall",
    chapter: "Integrated Recall and Command",
    anchor: "Physical geography, India map, monsoon, drainage, soils, resources, agriculture, world map integration",
    duration: "12 min",
    watch: "Run a cumulative recall circuit that links physical drivers with India and world map evidence.",
    talk: "Can you connect relief, climate, rivers, soils, resources, agriculture, and world map facts as one system?",
    test: "Fresh MCQ slot: integrated physical, India map, and world map drill.",
    track: "Build the full weak-area heatmap before mock practice.",
    revisit: "Re-explain every weak Day 1-17 concept before adding final PYQ load.",
    lab: "MCQ Engine",
  },
  {
    day: 19,
    week: 4,
    title: "Weak-Area Repair and PYQ Mock",
    chapter: "Integrated Recall and Command",
    anchor: "Personalized recovery, PYQ pattern reading, statement traps, atlas repair, mixed mock, error analysis",
    duration: "12 min",
    watch: "Repair only the tracked weak zones, then read PYQ traps and run a mixed mock.",
    talk: "What is the root cause of each repeated mistake: knowledge gap, map confusion, statement trap, or confidence error?",
    test: "Fresh MCQ slot: weak-area retest, PYQ-style mixed mock, and map repair.",
    track: "Compare original and retest confidence.",
    revisit: "Schedule remaining weak topics into the final command-day revision queue.",
    lab: "MCQ Engine",
  },
  {
    day: 20,
    week: 4,
    title: "Geography Command Day",
    chapter: "Integrated Recall and Command",
    anchor: "Final recall, maps, formulas, examples, PYQ traps, confidence audit, revision lock",
    duration: "12 min",
    watch: "Close the subject with fast full-syllabus recall, map confidence, PYQ traps, and revision scheduling.",
    talk: "Can every major Geography theme be explained through cause, location, map proof, and one UPSC trap?",
    test: "Fresh MCQ slot: command-day test and final error classification.",
    track: "Mark Geography as launch-ready, revision-needed, or retest-needed.",
    revisit: "Lock the next revision dates.",
    lab: "India Interactive Map",
  },
];
