import {
  BrainCircuit,
  ClipboardCheck,
  Compass,
  Earth,
  LineChart,
  LucideIcon,
  Map,
  Mountain,
  Orbit,
  PlayCircle,
  RefreshCcw,
  Route,
  ShieldAlert,
  Sprout,
  Target,
  Waves,
} from "lucide-react";

export type LearningStep = {
  label: string;
  detail: string;
  icon: LucideIcon;
  tone: string;
};

export type GeographySession = {
  day: number;
  week: number;
  title: string;
  chapter: string;
  anchor: string;
  duration: string;
  watch: string;
  talk: string;
  test: string;
  track: string;
  revisit: string;
  lab: string;
  gsCompatibility?: string;
  subtopics?: string[];
};

export const learningSteps: LearningStep[] = [
  {
    label: "Talk",
    detail: "Recall-first AI discussion",
    icon: BrainCircuit,
    tone: "bg-teal-50 text-teal-800 ring-teal-100",
  },
  {
    label: "Watch",
    detail: "Gap-repair concept session",
    icon: PlayCircle,
    tone: "bg-emerald-50 text-emerald-800 ring-emerald-100",
  },
  {
    label: "Test",
    detail: "MCQ and mains practice action",
    icon: ClipboardCheck,
    tone: "bg-amber-50 text-amber-800 ring-amber-100",
  },
  {
    label: "Track",
    detail: "Gap, confidence, and recall map",
    icon: LineChart,
    tone: "bg-slate-50 text-slate-800 ring-slate-200",
  },
  {
    label: "Revisit",
    detail: "Revision queue and weak-topic repair",
    icon: RefreshCcw,
    tone: "bg-stone-50 text-stone-800 ring-stone-200",
  },
];

export const upscCalendar = [
  {
    window: "Daily",
    title: "UPSC Daily Mission Control",
    detail: "Student launcher for the selected subject day, Watch, Talk, Lab, MCQ, Track, and Revisit.",
    status: "Structure ready",
    href: "/upsc/daily-command",
  },
  {
    window: "Product",
    title: "UPSC Yearly Planner",
    detail: "Pricing, yearly subject sequence, GS coverage layers, PYQ preload target, and three-day launch plan.",
    status: "Structure ready",
    href: "/upsc/yearly-planner",
  },
  {
    window: "Pricing",
    title: "UPSC Pricing Command",
    detail: "Rs 399 monthly base with yearly, 18-month, and three-year discount ladders for launch enrollment.",
    status: "Structure ready",
    href: "/upsc/pricing",
  },
  {
    window: "Optional",
    title: "Optional Subject Command",
    detail: "Paper I and Paper II page shell for every UPSC optional subject with syllabus and PYQ preload targets.",
    status: "Structure ready",
    href: "/upsc/optional-subjects",
  },
  {
    window: "Sources",
    title: "Syllabus and PYQ Library",
    detail: "Official source anchors, GS syllabus nodes, prelims/mains PYQ import rows, and optional Paper I/II ledger.",
    status: "Structure ready",
    href: "/upsc/source-library",
  },
  {
    window: "June",
    title: "Geography",
    detail: "First complete subject sprint with map-first learning.",
    status: "Build now",
    href: "/upsc/geography",
  },
  {
    window: "July 1-20",
    title: "Environment",
    detail: "Ecology, biodiversity, climate, conventions, current affairs.",
    status: "Structure ready",
    href: "/upsc/environment",
  },
  {
    window: "July 21-31",
    title: "Disaster Management",
    detail: "Risk, preparedness, institutions, case studies, answer writing.",
    status: "Structure ready",
    href: "/upsc/disaster-management",
  },
  {
    window: "August",
    title: "Economy",
    detail: "Core economy with budget, schemes, banking, inflation, growth.",
    status: "Structure ready",
    href: "/upsc/economy",
  },
  {
    window: "September",
    title: "Science and Tech",
    detail: "Applied science, emerging tech, space, biotech, defence tech.",
    status: "Structure ready",
    href: "/upsc/science-tech",
  },
  {
    window: "October",
    title: "Polity and Governance",
    detail: "Constitutional command plus governance application.",
    status: "Structure ready",
    href: "/upsc/polity-governance",
  },
  {
    window: "November",
    title: "Internal Security and Indian Society",
    detail: "Security frameworks, social change, vulnerable sections.",
    status: "Structure ready",
    href: "/upsc/internal-security-society",
  },
  {
    window: "December-January",
    title: "History",
    detail: "Modern, Ancient, Medieval, Art and Culture in four 15-day blocks.",
    status: "Structure ready",
    href: "/upsc/history",
  },
  {
    window: "Revision Phase",
    title: "All-Subject Revision Command",
    detail: "Global revisit queue, subject trackers, and command readiness across the full UPSC plan.",
    status: "Structure ready",
    href: "/upsc/revision-command",
  },
  {
    window: "Question Engine",
    title: "UPSC MCQ Command Center",
    detail: "Fresh MCQ batch planning, CSV contracts, upload links, and day-wise readiness.",
    status: "Structure ready",
    href: "/upsc/mcq-command",
  },
  {
    window: "Content Engine",
    title: "UPSC Content Command Center",
    detail: "Video, notes, transcript, source type, and Watch-room readiness across all class days.",
    status: "Structure ready",
    href: "/upsc/content-command",
  },
  {
    window: "Audit",
    title: "UPSC Readiness Audit Center",
    detail: "Local launch report for routes, subjects, content, MCQs, progress, and pending data work.",
    status: "Structure ready",
    href: "/upsc/readiness-audit",
  },
];

export const geographyWeeks = [
  {
    week: "Week 1",
    title: "Physical Geography Foundation",
    detail: "Earth evolution, geomorphology, climatology base, ocean basics.",
    icon: Earth,
  },
  {
    week: "Week 2",
    title: "India Map Command",
    detail: "Monsoon, rivers, soils, physiography, resources, agriculture.",
    icon: Map,
  },
  {
    week: "Week 3",
    title: "Human and Economic Geography",
    detail: "Population, settlements, transport, industries, regional patterns.",
    icon: Route,
  },
  {
    week: "Week 4",
    title: "Atlas, PYQ Logic, Revision",
    detail: "Map drills, integrated concepts, weak-area recovery, final tests.",
    icon: Target,
  },
];

export const geographyLabs = [
  {
    slug: "universe",
    title: "Universe Foundation Visual",
    detail: "Expansion, gravity, solar-disk accretion, differentiation, atmosphere and hydrosphere.",
    icon: Orbit,
  },
  {
    slug: "earth-layers",
    title: "Earth Layers Lab",
    detail: "Interior structure, plates, boundaries, earthquakes.",
    icon: Mountain,
  },
  {
    slug: "monsoon",
    title: "Monsoon Simulator",
    detail: "Pressure, winds, ITCZ movement, orographic rainfall.",
    icon: Waves,
  },
  {
    slug: "india-map",
    title: "India Interactive Map",
    detail: "Rivers, soils, vegetation, minerals, crops, climate zones.",
    icon: Compass,
  },
  {
    slug: "disaster-link",
    title: "Disaster Link",
    detail: "Floods, cyclones, landslides, droughts, mitigation logic.",
    icon: ShieldAlert,
  },
  {
    slug: "environment-bridge",
    title: "Environment Bridge",
    detail: "Biomes, climate change, biodiversity, conservation geography.",
    icon: Sprout,
  },
  {
    slug: "mcq-engine",
    title: "MCQ Engine",
    detail: "Fresh question upload, chapter test, daily mixed drill.",
    icon: ClipboardCheck,
  },
];

export const geographySessions: GeographySession[] = [
  {
    day: 1,
    week: 1,
    title: "Geographic Thinking and Map Relationships",
    chapter: "Geography Foundation",
    anchor: "What, where, why; absolute and relative location; site and situation; scale; India relationship drills",
    duration: "12 min",
    watch: "Learn how geography asks why here and not there, then use location, scale, site, situation, and map relationships to read India spatially.",
    talk: "Why is asking why here and not there more useful than memorizing isolated locations? Explain with one India map relationship.",
    test: "Fresh MCQ slot: geographic lens, absolute-relative location, site-situation, scale, and India relationship drills.",
    track: "Mark whether you can explain one location through relationship, scale, and an India map cue.",
    revisit: "Rebuild one India map relationship using what, where, why, site, situation, and scale.",
    lab: "India Interactive Map",
    gsCompatibility:
      "GS Paper I Geography foundation: spatial distribution, location logic, physical-human relationships, and applied India map reading.",
    subtopics: [
      "what, where, and why",
      "absolute and relative location",
      "site and situation",
      "geographic scale",
      "India map relationships",
    ],
  },
  {
    day: 2,
    week: 1,
    title: "Origin and Evolution of Earth",
    chapter: "Physical Geography Foundation",
    anchor: "Expansion of space, cooling, gravity, solar nebula, accretion, differentiation, atmosphere, hydrosphere",
    duration: "12 min",
    watch: "Follow one causal chain from expansion of space to a differentiated Earth with atmosphere and water.",
    talk: "How does expansion become a layered Earth, and why is Big Bang not simply an explosion into empty space?",
    test: "Fresh MCQ slot: expansion, accretion, differentiation, atmosphere and hydrosphere.",
    track: "Separate the causal sequence from disconnected universe facts.",
    revisit: "Speak the five-step chain: expansion, gravity, accretion, differentiation, atmosphere and hydrosphere.",
    lab: "Universe Foundation Visual",
    gsCompatibility:
      "GS Paper I Physical Geography foundation: origin of the universe, solar-system formation, evolution of Earth, differentiation, atmosphere, and hydrosphere.",
    subtopics: [
      "expansion of space",
      "cooling and gravity",
      "solar nebula and accretion",
      "Earth differentiation",
      "atmosphere and hydrosphere",
    ],
  },
  {
    day: 3,
    week: 1,
    title: "Interior of Earth and Plate Movement",
    chapter: "Physical Geography Foundation",
    anchor: "Seismic evidence, crust, mantle, core, lithosphere, asthenosphere, convection, plate boundaries",
    duration: "12 min",
    watch: "Use seismic evidence to read Earth layers, then connect mantle behavior with moving plates and hazard patterns.",
    talk: "How do seismic waves and mantle dynamics explain why earthquakes, volcanoes, and mountains are not randomly distributed?",
    test: "Fresh MCQ slot: Earth layers, seismic evidence, convection and plate boundaries.",
    track: "Map weak links between layers, wave behavior, convection and boundary types.",
    revisit: "Redraw Earth layers, then compare convergent, divergent, and transform boundaries.",
    lab: "Earth Layers Lab",
  },
  {
    day: 4,
    week: 1,
    title: "Geomorphic Processes",
    chapter: "Physical Geography Foundation",
    anchor: "Weathering, mass wasting, erosion, deposition",
    duration: "12 min",
    watch: "Understand internal and external forces shaping landforms.",
    talk: "Why does the same rock produce different landforms in different climates?",
    test: "Fresh MCQ slot: geomorphic agents and processes.",
    track: "Tag confusion between process and landform.",
    revisit: "Make one table of agent, process, and resulting landform.",
    lab: "Disaster Link",
  },
  {
    day: 5,
    week: 1,
    title: "Climatology Base",
    chapter: "Physical Geography Foundation",
    anchor: "Insolation, heat budget, pressure belts, winds",
    duration: "12 min",
    watch: "Build pressure and wind logic from unequal heating.",
    talk: "Why does air move, and why does it curve?",
    test: "Fresh MCQ slot: pressure belts and wind systems.",
    track: "Check if Coriolis, pressure gradient, and belts are conceptually clear.",
    revisit: "Sketch global pressure belts without notes.",
    lab: "Monsoon Simulator",
  },
  {
    day: 6,
    week: 1,
    title: "Ocean System",
    chapter: "Physical Geography Foundation",
    anchor: "Ocean relief, salinity, temperature, currents",
    duration: "12 min",
    watch: "Relate ocean currents with climate and coastal effects.",
    talk: "Why do currents matter for deserts, rainfall, fog, and fisheries?",
    test: "Fresh MCQ slot: ocean currents and salinity.",
    track: "Mark current-location pairs for map revision.",
    revisit: "Trace warm and cold currents on a blank world map.",
    lab: "Monsoon Simulator",
  },
  {
    day: 7,
    week: 1,
    title: "Physical Geography Consolidation",
    chapter: "Physical Geography Foundation",
    anchor: "Earth, tectonics, landforms, climate, ocean integration",
    duration: "12 min",
    watch: "Review the full physical base with integrated examples.",
    talk: "Which physical geography ideas explain most UPSC map questions?",
    test: "Fresh MCQ slot: mixed physical geography drill.",
    track: "Generate the first weak-topic list.",
    revisit: "Reattempt weak concepts from Days 1-6.",
    lab: "Earth Layers Lab",
  },
  {
    day: 8,
    week: 2,
    title: "India Physiography",
    chapter: "India Map Command",
    anchor: "Himalayas, plains, plateau, desert, coast, islands",
    duration: "12 min",
    watch: "Build India relief as a map-first framework.",
    talk: "How does relief control rivers, climate, soils, agriculture, and risk?",
    test: "Fresh MCQ slot: physiographic divisions.",
    track: "Map blank zones where recall is weak.",
    revisit: "Draw India physiographic divisions from memory.",
    lab: "India Interactive Map",
  },
  {
    day: 9,
    week: 2,
    title: "Indian Drainage",
    chapter: "India Map Command",
    anchor: "Himalayan and peninsular rivers, basins, tributaries",
    duration: "12 min",
    watch: "Understand drainage through slope, origin, and basin behavior.",
    talk: "Why do Himalayan and peninsular rivers behave differently?",
    test: "Fresh MCQ slot: rivers and tributaries.",
    track: "Tag river-origin, tributary, and state-location errors.",
    revisit: "Trace major rivers and tributaries on a blank map.",
    lab: "India Interactive Map",
  },
  {
    day: 10,
    week: 2,
    title: "Indian Monsoon",
    chapter: "India Map Command",
    anchor: "ITCZ, jet streams, onset, break, retreat, variability",
    duration: "12 min",
    watch: "Build monsoon as a moving pressure-wind-rainfall system.",
    talk: "Why is the monsoon powerful but unreliable?",
    test: "Fresh MCQ slot: monsoon mechanism.",
    track: "Separate mechanism errors from factual rainfall errors.",
    revisit: "Explain monsoon onset and retreat in five steps.",
    lab: "Monsoon Simulator",
  },
  {
    day: 11,
    week: 2,
    title: "Climate Regions of India",
    chapter: "India Map Command",
    anchor: "Rainfall distribution, temperature, western disturbances",
    duration: "12 min",
    watch: "Connect India climate patterns with topography and winds.",
    talk: "Why do nearby places receive very different rainfall?",
    test: "Fresh MCQ slot: Indian climate and rainfall.",
    track: "Mark region-wise rainfall confidence.",
    revisit: "Build a rainfall map from memory.",
    lab: "Monsoon Simulator",
  },
  {
    day: 12,
    week: 2,
    title: "Soils and Vegetation",
    chapter: "India Map Command",
    anchor: "Soil types, forest types, distribution, conservation",
    duration: "12 min",
    watch: "Link soil and vegetation with climate, rock, relief, and use.",
    talk: "Why do soil and vegetation questions often test geography plus environment?",
    test: "Fresh MCQ slot: soils and natural vegetation.",
    track: "Tag soil-location-crop confusion.",
    revisit: "Match soil, region, crop, and limitation.",
    lab: "Environment Bridge",
  },
  {
    day: 13,
    week: 2,
    title: "Resources and Agriculture",
    chapter: "India Map Command",
    anchor: "Minerals, energy, irrigation, crops, agro-climatic logic",
    duration: "12 min",
    watch: "Connect resources and agriculture with location advantages.",
    talk: "Why do crops, minerals, and industries cluster where they do?",
    test: "Fresh MCQ slot: resources and agriculture.",
    track: "Map resource belts and crop belts.",
    revisit: "Build one crop-mineral-region grid.",
    lab: "India Interactive Map",
  },
  {
    day: 14,
    week: 2,
    title: "India Map Drill",
    chapter: "India Map Command",
    anchor: "Relief, rivers, climate, soils, resources integration",
    duration: "12 min",
    watch: "Run an integrated blank-map recap.",
    talk: "Which India map facts become easy when the cause is known?",
    test: "Fresh MCQ slot: India map mixed drill.",
    track: "Generate India map weak areas.",
    revisit: "Repair the weakest five map locations.",
    lab: "India Interactive Map",
  },
  {
    day: 15,
    week: 3,
    title: "Population Geography",
    chapter: "Human and Economic Geography",
    anchor: "Density, distribution, migration, demographic transition",
    duration: "12 min",
    watch: "Study population patterns through resources, economy, and risk.",
    talk: "Why do people cluster in some regions and avoid others?",
    test: "Fresh MCQ slot: population concepts.",
    track: "Mark concept gaps in density, growth, and migration.",
    revisit: "Compare density, distribution, and demographic transition.",
    lab: "India Interactive Map",
  },
  {
    day: 16,
    week: 3,
    title: "Settlements",
    chapter: "Human and Economic Geography",
    anchor: "Rural and urban settlements, hierarchy, morphology",
    duration: "12 min",
    watch: "Understand settlement patterns through function and geography.",
    talk: "Why do settlements take different shapes and functions?",
    test: "Fresh MCQ slot: settlements.",
    track: "Separate definition recall from application errors.",
    revisit: "Map examples of settlement types.",
    lab: "India Interactive Map",
  },
  {
    day: 17,
    week: 3,
    title: "Economic Activities",
    chapter: "Human and Economic Geography",
    anchor: "Primary, secondary, tertiary, quaternary activities",
    duration: "12 min",
    watch: "Connect activities with resources, technology, and markets.",
    talk: "Why does economic geography shift over time?",
    test: "Fresh MCQ slot: economic activities.",
    track: "Mark confusion across activity categories.",
    revisit: "Create examples for each economic activity type.",
    lab: "India Interactive Map",
  },
  {
    day: 18,
    week: 3,
    title: "Transport and Trade",
    chapter: "Human and Economic Geography",
    anchor: "Transport networks, ports, corridors, trade routes",
    duration: "12 min",
    watch: "Study connectivity as a geographic and economic force.",
    talk: "Why do corridors and ports transform regions?",
    test: "Fresh MCQ slot: transport and trade.",
    track: "Map corridor and port recall.",
    revisit: "Trace major transport corridors and ports.",
    lab: "India Interactive Map",
  },
  {
    day: 19,
    week: 3,
    title: "Industry Location",
    chapter: "Human and Economic Geography",
    anchor: "Factors of industrial location, regions, resource-market logic",
    duration: "12 min",
    watch: "Build industry location through input, labor, power, market, and policy.",
    talk: "Why do old and new industrial regions form differently?",
    test: "Fresh MCQ slot: industry location.",
    track: "Tag factor-example mismatches.",
    revisit: "Compare iron-steel, textile, IT, and petrochemical locations.",
    lab: "India Interactive Map",
  },
  {
    day: 20,
    week: 3,
    title: "Regional Development",
    chapter: "Human and Economic Geography",
    anchor: "Planning regions, disparities, urbanization, sustainability",
    duration: "12 min",
    watch: "Connect geography with development choices and constraints.",
    talk: "Why does development produce spatial inequality?",
    test: "Fresh MCQ slot: regional development.",
    track: "Mark weak governance-geography connections.",
    revisit: "Build examples of regional disparity and planning.",
    lab: "Environment Bridge",
  },
  {
    day: 21,
    week: 3,
    title: "Human Geography Consolidation",
    chapter: "Human and Economic Geography",
    anchor: "Population, settlements, economy, transport, industry integration",
    duration: "12 min",
    watch: "Review human and economic geography through integrated maps.",
    talk: "Which human geography ideas repeat in prelims and mains?",
    test: "Fresh MCQ slot: mixed human geography drill.",
    track: "Generate human geography weak-topic list.",
    revisit: "Repair the weakest three human geography concepts.",
    lab: "India Interactive Map",
  },
  {
    day: 22,
    week: 4,
    title: "Atlas Mastery",
    chapter: "Atlas, PYQ Logic, Revision",
    anchor: "World and India map orientation, recurring locations",
    duration: "12 min",
    watch: "Convert atlas reading into exam-relevant map recall.",
    talk: "How can a map fact become a concept question?",
    test: "Fresh MCQ slot: atlas drill.",
    track: "Track map recall speed and accuracy.",
    revisit: "Reopen every wrong map location.",
    lab: "India Interactive Map",
  },
  {
    day: 23,
    week: 4,
    title: "PYQ Pattern Reading",
    chapter: "Atlas, PYQ Logic, Revision",
    anchor: "Question traps, statement logic, recurring themes",
    duration: "12 min",
    watch: "Study how UPSC frames geography statements.",
    talk: "What makes a geography statement tricky rather than difficult?",
    test: "Fresh MCQ slot: PYQ-style concept drill.",
    track: "Tag traps by location, process, exception, and pair matching.",
    revisit: "Rewrite five wrong statements into correct statements.",
    lab: "MCQ Engine",
  },
  {
    day: 24,
    week: 4,
    title: "Disaster Geography Bridge",
    chapter: "Atlas, PYQ Logic, Revision",
    anchor: "Cyclones, floods, droughts, landslides, earthquakes",
    duration: "12 min",
    watch: "Link physical geography with disaster management.",
    talk: "Why does the same hazard become a different disaster in different regions?",
    test: "Fresh MCQ slot: disaster geography.",
    track: "Mark hazard-vulnerability-response gaps.",
    revisit: "Build hazard maps for India.",
    lab: "Disaster Link",
  },
  {
    day: 25,
    week: 4,
    title: "Environment Geography Bridge",
    chapter: "Atlas, PYQ Logic, Revision",
    anchor: "Biomes, climate change, biodiversity, conservation regions",
    duration: "12 min",
    watch: "Connect geography with environment and ecology.",
    talk: "Why do environment questions often start with geography?",
    test: "Fresh MCQ slot: environment-geography bridge.",
    track: "Mark biome, climate, and conservation location gaps.",
    revisit: "Build biome-climate-region examples.",
    lab: "Environment Bridge",
  },
  {
    day: 26,
    week: 4,
    title: "Mains Geography Application",
    chapter: "Atlas, PYQ Logic, Revision",
    anchor: "Concept to answer writing, diagrams, examples",
    duration: "12 min",
    watch: "Convert geography concepts into mains-ready explanations.",
    talk: "How can a map or diagram improve a geography answer?",
    test: "Fresh practice slot: 10 marker plus MCQ recap.",
    track: "Track examples, diagrams, and structure quality.",
    revisit: "Rewrite one weak answer with map support.",
    lab: "India Interactive Map",
  },
  {
    day: 27,
    week: 4,
    title: "Full Geography Drill",
    chapter: "Atlas, PYQ Logic, Revision",
    anchor: "Physical, India, human, atlas, environment integration",
    duration: "12 min",
    watch: "Run the full subject recap at high speed.",
    talk: "Which concepts now connect multiple chapters?",
    test: "Fresh MCQ slot: full geography mixed drill.",
    track: "Build final weak-area heatmap.",
    revisit: "Revisit every low-confidence topic.",
    lab: "MCQ Engine",
  },
  {
    day: 28,
    week: 4,
    title: "Weak Area Repair",
    chapter: "Atlas, PYQ Logic, Revision",
    anchor: "Personalized recovery from tracked weak zones",
    duration: "12 min",
    watch: "Review only the weak zones identified by practice.",
    talk: "What is the root cause of each repeated mistake?",
    test: "Fresh MCQ slot: weak-area retest.",
    track: "Compare original and retest confidence.",
    revisit: "Schedule remaining weak topics into revision.",
    lab: "MCQ Engine",
  },
  {
    day: 29,
    week: 5,
    title: "Final Mock and Review",
    chapter: "Command Phase",
    anchor: "Full mock, error analysis, map repair",
    duration: "12 min",
    watch: "Review only after completing the full mock.",
    talk: "Which mistakes were knowledge gaps, reading errors, or confidence errors?",
    test: "Fresh MCQ slot: final Geography mock.",
    track: "Classify mistakes into repair categories.",
    revisit: "Create final 24-hour revision queue.",
    lab: "MCQ Engine",
  },
  {
    day: 30,
    week: 5,
    title: "Geography Command Day",
    chapter: "Command Phase",
    anchor: "Final recall, maps, formulas, examples, confidence",
    duration: "12 min",
    watch: "Close the subject with a fast full-syllabus recall.",
    talk: "Can every major Geography theme be explained through cause and location?",
    test: "Fresh MCQ slot: command-day test.",
    track: "Mark Geography as launch-ready, revision-needed, or retest-needed.",
    revisit: "Lock the next revision dates.",
    lab: "India Interactive Map",
  },
];
